# RUN:
#  scripts/patch-cutdown-playbook antora-playbook.preview2

antora:
  extensions:
  - ./lib/report-tree.js

site:
  title: Couchbase Docs Preview
  robots: disallow

content:
  $select:
    - '.'
    - '**/docs-columnar'
    - '**/docs-enterprise-analytics'
    - '**/docs-analytics'

  sources: []
   # - url: https://github.com/couchbase/docs-capella
     # branches: [AV-115233-azure-cmek-support]

asciidoc:
  attributes:
    kroki-server-url: null
    page-show-preview-banner: false
    page-watermark: preview2@

#ui:
  #bundle:
    #url: https://github.com/couchbase/docs-ui/releases/download/prod-217/ui-bundle.zip
