# npx antora --clean --fetch antora-playbook.yml
# or
# npx antora antora-playbook.yml
antora:
  extensions:
  - '@antora/site-generator-ms'
  - ./lib/embargo.js
  - "@antora/collector-extension"
site:
  title: Couchbase Docs Staging
  url: https://docs-staging.couchbase.com
  start_page: home::index.adoc
  robots: disallow
  keys:
    nav_groups: |
      [
        { "title": "Server", "startPage": "home::server.adoc", "components": ["server"] },
        { "title": "Mobile", "startPage": "home::mobile.adoc", "components": ["couchbase-lite", "sync-gateway"] },
        { "title": "Capella", "startPage": "cloud::index.adoc", "components": ["cloud"] },
        { "title": "Cloud-Native", "startPage": "cloud-native-database::index.adoc", "components": ["cloud-native-database"] },
        { "title": "Autonomous Operator", "components": ["operator"] },
        { "title": "CMOS", "components": ["cmos"] },
        { "title": "SDKs", "startPage": "home::sdk.adoc", "components": ["*-sdk", "cxx-txns", "elasticsearch-connector", "kafka-connector", "spark-connector", "tableau-connector", "power-bi-connector", "sdk-extensions"] },
        { "title": "Tutorials", "startPage": "tutorials::index.adoc", "components": ["tutorials"] }
      ]
git:
  ensure_git_suffix: false
  fetch_concurrency: 1
urls:
  latest_version_segment_strategy: redirect:to
  latest_version_segment: current
content:
  branches: master
  # NOTE the git@ segment in the URL indicates which repositories are private
  ## The above has a bug when upgrading to Antora 3.1. Original sources commented
  ## out and replaced with a non git@ prefix. To revert if it causes issues
  sources:
  - url: .
    branches: HEAD
    start_path: home
  - url: https://github.com/couchbaselabs/docs-devex
    branches: [release/7.6, release/7.2, capella, elixir]
  - url: https://github.com/couchbaselabs/cb-swagger
    branches: [release/7.6, release/7.2, release/7.1, release/7.0, release/6.6, capella, elixir]
    start_path: docs
  #- url: https://git@github.com/couchbasecloud/couchbase-cloud
  - url: https://github.com/couchbasecloud/couchbase-cloud
    branches: [main]
    start_path: docs/public
  # - url: https://git@github.com/couchbase/couchbase-operator
  - url: https://github.com/couchbase/couchbase-operator
    branches: [master, 2.6.x, 2.5.x, 2.4.x, 2.3.x, 2.2.x, 2.1.x]
    start_path: docs/user
  - url: https://github.com/couchbaselabs/observability
    branches: [main]
    start_path: docs
  - url: https://github.com/couchbaselabs/cbmultimanager
    branches: [master]
    start_path: docs
  - url: https://github.com/couchbase/couchbase-elasticsearch-connector
    branches: [master, release/4.3]
    start_path: docs
  - url: https://github.com/couchbase/kafka-connect-couchbase
    branches: [master, release/4.1]
    start_path: docs
  - url: https://github.com/couchbase/couchbase-spark-connector
    branches: [master, release/3.2, release/3.1]
    start_path: docs
  - url: https://github.com/couchbase/couchbase-tableau-connector
    branches: [master]
    start_path: docs
  - url: https://github.com/couchbase/docs-connectors-power-bi
    branches: [main]
  # - url: https://git@github.com/couchbase/docs-connectors-talend
  - url: https://github.com/couchbase/docs-connectors-talend
  # - url: https://git@github.com/couchbase/docs-analytics
  - url: https://github.com/couchbase/docs-analytics
    branches: [release/7.6, release/7.2, release/7.1, release/7.0, release/6.6]
  - url: https://github.com/couchbase/couchbase-cli
    branches: [master, neo, 7.1.x-docs, cheshire-cat]
    start_path: docs
  # - url: https://git@github.com/couchbase/backup
  - url: https://github.com/couchbase/backup
    branches: [master, neo, 7.1.x-docs, cheshire-cat]
    start_path: docs
  # NOTE docs-server is currently after other server repos so nav key wins
  - url: https://github.com/couchbase/docs-server
    branches: [release/7.6, release/7.2, release/7.1, release/7.0, release/6.6]
  - url: https://github.com/couchbase/docs-sdk-common
    branches: [temp/7.5, release/7.2, release/7.1.2, release/7.1, release/7.0, release/6.6]
  - url: https://github.com/couchbase/docs-sdk-c
    branches: [release/3.3, release/3.2]
  - url: https://github.com/couchbase/docs-txn-cxx
    branches: [release/1.0]
  - url: https://github.com/couchbase/docs-sdk-dotnet
    branches: [release/3.5, release/3.4, release/3.3, release/3.2]
  - url: https://github.com/couchbase/docs-sdk-go
    branches: [temp/2.8, release/2.7, release/2.6, release/2.5, release/2.4, release/2.3]
  - url: https://github.com/couchbase/docs-sdk-java
    branches: [temp/3.6, release/3.5, release/3.4, release/3.3, release/3.2]
  - url: https://github.com/couchbase/docs-sdk-kotlin
    branches: [temp/1.3, release/1.2, release/1.1, release/1.0]
  - url: https://github.com/couchbase/docs-sdk-nodejs
    branches: [temp/4.3, release/4.2, release/4.1, release/4.0, release/3.2]
  - url: https://github.com/couchbase/docs-sdk-php
    branches: [temp/4.2, release/4.1, release/4.0, release/3.2, release/3.1]
  - url: https://github.com/couchbase/docs-sdk-python
    branches: [temp/4.2, release/4.1, release/4.0, release/3.2]
  - url: https://github.com/couchbase/docs-sdk-ruby
    branches: [temp/3.5, release/3.4, release/3.3, release/3.2]
  - url: https://github.com/couchbase/docs-sdk-scala
    branches: [temp/1.6, release/1.5, release/1.4, release/1.3, release/1.2]
  - url: https://github.com/couchbase/docs-sdk-extensions
    branches: [main]
    # Mobile Docs Pages
  - url: https://github.com/couchbase/docs-mobile
    branches: [release/3.1, release/2.8]
  - url: https://github.com/couchbaselabs/docs-couchbase-lite
    branches: [release/3.1, release/3.0, release/2.8]
  - url: https://github.com/couchbaselabs/docs-sync-gateway
    branches: [release/3.1, release/3.0, release/2.8]
  - url: https://github.com/couchbase/docs-service-broker
    branches: [1.1.x, 1.2.x]
  # - url: https://git@github.com/couchbase/docs-cloud-native
  - url: https://github.com/couchbase/docs-cloud-native
    branches: [cloud-native-2.2]
#  - url: https://github.com/couchbaselabs/tutorials
  - url: https://github.com/couchbase/developer-content
  - url: https://github.com/couchbaselabs/tutorial-template
  - url: https://github.com/couchbaselabs/mobile-travel-sample
    branches: [master]
    start_path: content
  # - url: https://github.com/couchbaselabs/hotel-finder-react-native
  # - url: https://github.com/couchbaselabs/hotel-lister-cordova
#  - url: https://github.com/couchbaselabs/tutorials-contrib
  - url: https://github.com/couchbaselabs/mobile-training-todo
    branches: tutorials
    start_path: content
  - url: https://github.com/couchbaselabs/UniversityLister-Android
    start_path: content
  - url: https://github.com/couchbaselabs/userprofile-couchbase-mobile
    branches: [standalone, query, sync, backgroundfetch]
    start_path: content
  - url: https://github.com/couchbaselabs/userprofile-couchbase-mobile-xamarin
    branches: [standalone, query, sync]
    start_path: content
  - url: https://github.com/couchbaselabs/userprofile-couchbase-mobile-android
    branches: [standalone, query, sync]
    start_path: content
  # - url: https://github.com/amarantha-k/OpenID_connect_tutorial
  #   branches: [tutorial]
  #   start_path: content
  - url: https://github.com/couchbaselabs/couchbase-lite-peer-to-peer-sync-examples
    branches: [master]
    start_path: content
asciidoc:
  attributes:
    site-navigation-data-path: _/js/site-navigation-data.js
    enable-cmos: ''
    max-include-depth: 10
    page-partial: false
    experimental: ''
    idprefix: '@'
    idseparator: '-@'
    tabs: tabs
    tabs-sync-option: ''
    toc: ~
    page-toclevels: 1@
    xrefstyle: short
    enterprise: https://www.couchbase.com/products/editions[ENTERPRISE EDITION]
    community: https://www.couchbase.com/products/editions[COMMUNITY EDITION]
    sqlpp: SQL++
    sqlpp_url: https://www.couchbase.com/products/n1ql
    cbpp: Couchbase++
    kroki-server-url: http://3.91.133.254:9500
    kroki-fetch-diagram: true
  extensions:
  - ./lib/source-url-include-processor.js
  - ./lib/json-config-ui-block-macro.js
  - ./lib/inline-man-macro.js
  - ./lib/multirow-table-head-tree-processor.js
  - ./lib/swagger-ui-block-macro.js
  - ./lib/markdown-block.js
  - ./lib/template-block.js
  - asciidoctor-kroki
  - asciidoctor-external-callout
  - '@asciidoctor/tabs'
ui:
  bundle:
    url: https://github.com/couchbase/docs-ui/releases/download/prod-180/ui-bundle.zip
output:
  dir: ./public
