# RUN:
#  scripts/patch-cutdown-playbook antora-playbook.preview2

antora:
  extensions:
  - ./lib/report-tree.js

site:
  title: Couchbase Docs Preview Polaris
  robots: disallow

content:
  $prune: 1
  $select:
    - '.'
    - '**/docs-columnar'
    - '**/docs-enterprise-analytics'
    - '**/docs-analytics'
    - '**/docs-capella'
    - '**/docs-server'
    - '**/docs-devex'
    - '**/cb-swagger'
    - '**/docs-connectors-power-bi'
    - '**/docs-tableau'
    - '**/docs-sdk-java'
    - '**/docs-sdk-common'
    - '**/couchbase-cli'

  sources:
   - url: https://github.com/couchbaselabs/docs-columnar
     branches:
       $replace: [ DOC-14627-analytics-url-rename-columnar ]
   - url: https://github.com/couchbaselabs/docs-enterprise-analytics
     branches:
       $replace: [ DOC-14629-Restructure-EA ]
   - url: https://github.com/couchbaselabs/docs-devex
     branches:
       - capella

asciidoc:
  attributes:
    docs-contact: Zeba
    kroki-server-url: null
    page-show-preview-banner: false
    page-watermark: Polaris

#ui:
  #bundle:
    #url: https://github.com/couchbase/docs-ui/releases/download/prod-217/ui-bundle.zip
