# RUN:
#  scripts/patch-cutdown-playbook antora-playbook.preview2

antora:
  extensions:
  - ./lib/report-tree.js

site:
  title: Couchbase Docs Preview Polaris
  robots: disallow

content:
  $prune: 1
  $select:
    - '.'
    - '**'

  sources:
   - url: https://github.com/couchbaselabs/docs-columnar
     branches:
       $replace: [ DOC-14645-Rename-CA-as-Operational-Insights-Capella ]
   - url: https://github.com/couchbaselabs/docs-enterprise-analytics
     branches:
       $replace: [ merge-prs/release/3.0, release/2.2, release/2.1, release/2.0 ]
   - url: https://github.com/couchbaselabs/docs-devex
     branches:
       - capella
   - url: https://github.com/couchbaselabs/docs-ai
     branches: DOC-14735_analytics-rename
   - url: https://github.com/couchbase/docs-capella
     branches: DOC-14735_analytics-rename

   - url: https://github.com/couchbase/docs-columnar-sdk-common
     branches: 
       $replace: [DOC-14641--oi-renaming]
   - url: https://github.com/couchbase/docs-columnar-sdk-go
     branches: 
       $replace: [DOC-14641--oi-renaming]
   - url: https://github.com/couchbase/docs-columnar-sdk-java
     branches: 
       $replace: [DOC-14641--oi-renaming]
   - url: https://github.com/couchbase/docs-columnar-sdk-nodejs
     branches: 
       $replace: [DOC-14641--oi-renaming]
   - url: https://github.com/couchbase/docs-columnar-sdk-python
     branches: 
       $replace: [DOC-14641--oi-renaming]

asciidoc:
  attributes:
    docs-contact: Zeba
    page-show-preview-banner: true
    page-hide-preview-link: true
    page-watermark: Polaris

ui:
  bundle:
    url: https://github.com/couchbase/docs-ui/releases/download/prod-238/ui-bundle.zip
