antora:
  extensions:
  - '@antora/site-generator-ms'
site:
  title: Couchbase Docs Archive
  url: https://docs-archive.couchbase.com
  start_page: home::index.adoc
  robots: disallow
git:
  ensure_git_suffix: false
  fetch_concurrency: 1
content:
  sources:
  - url: .
    branches: HEAD
    start_path: home
  - url: https://github.com/couchbaselabs/cb-swagger
    branches: [release/6.6, release/6.5, release/6.0]
    start_path: docs
  - url: https://github.com/couchbase/couchbase-operator
    branches: [2.1.x, 2.0.x, 1.2.x, 1.1.x, 1.0.x]
    start_path: docs/user
#  - url: https://github.com/couchbaselabs/observability
#    branches: [0.2.x]
#    start_path: docs
#  - url: https://github.com/couchbaselabs/cbmultimanager
#    branches: [0.2.x]
#    start_path: docs
  - url: https://github.com/couchbase/couchbase-elasticsearch-connector
    branches: [release/4.3, release/4.2, release/4.1, release/4.0, release/cypress]
    start_path: docs
  - url: https://github.com/couchbase/kafka-connect-couchbase
    branches: [release/4.0, release/3.4, release/3.3]
    start_path: docs
  - url: https://github.com/couchbase/couchbase-spark-connector
    branches: [release/2.4, release/2.3, release/2.2, release/2.1]
    start_path: docs
  - url: https://github.com/couchbase/docs-server
    branches: [release/6.6, release/6.5, release/6.0, release/5.5, release/5.1, release/5.0, release/4.6, release/4.5, release/4.1, release/4.0]
  - url: https://github.com/couchbase/docs-sdk-common
    branches: [release/6.6, release/6.5, release/6.0, release/5.5, release/5.1, release/4.6, release/4.5]
  - url: https://github.com/couchbase/docs-sdk-c
    branches: [release/3.2, release/3.1, release/3.0, release/2.10, release/2.9, release/2.8, release/2.7, release/2.6, release/2.5]
  - url: https://github.com/couchbase/docs-sdk-dotnet
    branches: [release/3.2, release/3.1, release/3.0, release/2.7, release/2.6, release/2.5, release/2.4, release/2.3, release/2.2, release/2.1]
  - url: https://github.com/couchbase/docs-sdk-go
    branches: [release/2.3, release/2.2, release/2.1, release/2.0, release/1.6, release/1.5, release/1.4, release/1.3, release/1.2, release/1.1, release/1.0]
  - url: https://github.com/couchbase/docs-sdk-java
    branches: [release/3.2, release/3.1, release/3.0, release/2.7, release/2.6, release/2.5, release/2.4, release/2.3, release/2.2, release/2.1]
  - url: https://github.com/couchbase/docs-sdk-nodejs
    branches: [release/3.2, release/3.1, release/3.0, release/2.6, release/2.5, release/2.4, release/2.3, release/2.2, release/2.1]
  - url: https://github.com/couchbase/docs-sdk-php
    branches: [release/3.2, release/3.1, release/3.0, release/2.6, release/2.5, release/2.4, release/2.3, release/2.2, release/2.1]
  - url: https://github.com/couchbase/docs-sdk-python
    branches: [release/3.2, release/3.1, release/3.0, release/2.5, release/2.4, release/2.3, release/2.2, release/2.1, release/2.0]
  - url: https://github.com/couchbase/docs-sdk-ruby
    branches: [release/3.2, release/3.1, release/3.0]
  - url: https://github.com/couchbase/docs-sdk-scala
    branches: [release/1.2, release/1.1, release/1.0]
  - url: https://github.com/couchbaselabs/docs-couchbase-lite
    branches: [release/2.7, release/2.6, release/2.5, release/2.1, release/2.0, release/1.4, release/1.3]
  - url: https://github.com/couchbaselabs/docs-sync-gateway
    branches: [release/2.7, release/2.6, release/2.5, release/2.1, release/2.0, release/1.5, release/1.4, release/1.3]
  - url: https://github.com/couchbase/docs-service-broker
    branches: [1.2.x, 1.1.x, 1.0.x]
  - url: https://git@github.com/couchbase/backup
    branches: [mad-hatter, 6.5.x-docs, alice, vulcan, spock, 5.0.x]
    start_path: docs
  - url: https://github.com/couchbase/couchbase-cli
    branches: [mad-hatter, 6.5.x-docs]
    start_path: docs
  - url: https://git@github.com/couchbase/docs-analytics
    branches: [release/6.6, release/6.5, release/6.0, release/5.5]
asciidoc:
  attributes:
    max-include-depth: 10
    page-partial: false
    primary-site-url: https://docs.couchbase.com
    experimental: ''
    idprefix: '@'
    idseparator: '-@'
    tabs: tabs
    toc: ~
    xrefstyle: short
    enterprise: https://www.couchbase.com/products/editions[ENTERPRISE EDITION]
    community: https://www.couchbase.com/products/editions[COMMUNITY EDITION]
    sqlpp: SQL++
    sqlpp_url: https://www.couchbase.com/products/n1ql
    cbpp: Couchbase++
    kroki-server-url: http://3.91.133.254:9500
    kroki-fetch-diagram: true
    # the url-issues and url-issues-* attributes configure the URLs for the inline jira macro
  extensions:
  - ./lib/source-url-include-processor.js
  - ./lib/json-config-ui-block-macro.js
  - ./lib/inline-man-macro.js
  - ./lib/multirow-table-head-tree-processor.js
  - ./lib/swagger-ui-block-macro.js
  - ./lib/markdown-block.js
  - ./lib/template-block.js
  - asciidoctor-kroki
  - asciidoctor-external-callout
  - '@asciidoctor/tabs'
ui:
  bundle:
    url: https://github.com/couchbase/docs-ui/releases/download/archive-1/ui-bundle.zip
output:
  dir: ./public
