# npx antora --clean --fetch antora-playbook.yml
# or
# npx antora antora-playbook.yml
antora:
  extensions:
  - '@antora/site-generator-ms'
  - ./lib/embargo.js
  - "@antora/collector-extension"
  - ./lib/antora-component-version-rank.js
  - ./lib/report-tree.js
site:
  title: Couchbase Docs Staging
  url: https://docs-staging.couchbase.com
  start_page: home::index.adoc
  robots: |
    User-agent: *
    Disallow: /

    User-agent: Algolia Crawler
    Allow: /
  keys:
    nav_groups: |
      [
        { "title": "Server", "startPage": "home::server.adoc", "components": ["server"] },
        { "title": "Mobile", "startPage": "home::mobile.adoc", "components": ["couchbase-lite", "sync-gateway"] },
        { "title": "Capella", "startPage": "home::cloud.adoc", "components": ["cloud", "columnar"] },
        { "title": "Cloud-Native", "startPage": "cloud-native-database::index.adoc", "components": ["cloud-native-database"] },
        { "title": "Autonomous Operator", "components": ["operator"] },
        { "title": "CMOS", "components": ["cmos"] },
        { "title": "Couchbase SDKs", "startPage": "home::sdk.adoc", "components": ["dotnet-sdk", "c-sdk", "cxx-sdk", "go-sdk", "java-sdk", "kotlin-sdk", "nodejs-sdk", "php-sdk", "python-sdk", "ruby-sdk", "scala-sdk", "elasticsearch-connector", "kafka-connector", "spark-connector", "tableau-connector", "power-bi-connector", "superset-connector", "sdk-extensions"] },
        { "title": "Columnar SDKs", "startPage": "home::columnar-sdk.adoc", "components": ["*-columnar-sdk"] },
        { "title": "Contribute", "components": ["home", "styleguide", "ui-ux", "pendo"] }
      ]
git:
  ensure_git_suffix: false
  fetch_concurrency: 1
urls:
  latest_version_segment_strategy: redirect:to
  latest_version_segment: current
content:
  branches: master
  # NOTE the git@ segment in the URL indicates which repositories are private
  ## The above has a bug when upgrading to Antora 3.1. Original sources commented
  ## out and replaced with a non git@ prefix. To revert if it causes issues
  sources:
  - url: .
    branches: HEAD
    start_path: home
  - url: https://github.com/couchbaselabs/docs-style-guide
    branches: main
    start_paths: [styleguide, ui-ux, pendo]
  - url: https://github.com/couchbaselabs/docs-devex
    branches: [prerelease/7.6.4, capella]
  - url: https://github.com/couchbaselabs/cb-swagger
    branches: [prerelease/7.6.4, capella]
    start_path: docs
  - url: https://github.com/couchbasecloud/couchbase-cloud
    branches: [main]
    start_paths: [docs/public, docs/columnar]
  - url: https://github.com/couchbase/docs-capella
    branches: [main]
  - url: https://github.com/couchbaselabs/docs-columnar
    branches: [main]
  # - url: https://git@github.com/couchbase/couchbase-operator
  - url: https://github.com/couchbase/couchbase-operator
    branches: [master]
    start_path: docs/user
  - url: https://github.com/couchbaselabs/observability
    branches: [main]
    start_path: docs
  - url: https://github.com/couchbaselabs/cbmultimanager
    branches: [master]
    start_path: docs
  - url: https://github.com/couchbase/docs-elastic-search
    branches: [main]
  - url: https://github.com/couchbase/docs-kafka
    branches: [main]
  - url: https://github.com/couchbase/docs-spark
    branches: [release/3.5]
  - url: https://github.com/couchbase/docs-tableau
    branches: [release/1.1]
  - url: https://github.com/couchbase/docs-connectors-power-bi
    branches: [main]
  - url: https://github.com/couchbase/docs-connectors-superset.git
    branches: [release/1.0]
  # - url: https://git@github.com/couchbase/docs-connectors-talend
  - url: https://github.com/couchbase/docs-connectors-talend
  # - url: https://git@github.com/couchbase/docs-analytics
  - url: https://github.com/couchbase/docs-analytics
    branches: [release/7.6]
  - url: https://github.com/couchbase/couchbase-cli
    branches: [trinity]
    start_path: docs
  # - url: https://git@github.com/couchbase/backup
  - url: https://github.com/couchbase/backup
    branches: [trinity]
    start_path: docs
  # NOTE docs-server is currently after other server repos so nav key wins
  - url: https://github.com/couchbase/docs-server
    branches: [release/7.6]
  - url: https://github.com/couchbase/docs-sdk-common
    branches: [release/7.6]
  - url: https://github.com/couchbase/docs-sdk-c
    branches: [release/3.3]
  - url: https://github.com/couchbase/docs-sdk-cxx
    branches: [release/1.0]
  - url: https://github.com/couchbase/docs-sdk-dotnet
    branches: [temp/3.6]
  - url: https://github.com/couchbase/docs-sdk-go
    branches: [temp/2.9]
  - url: https://github.com/couchbase/docs-sdk-java
    branches: [temp/3.7]
  - url: https://github.com/couchbase/docs-sdk-kotlin
    branches: [temp/1.4]
  - url: https://github.com/couchbase/docs-sdk-nodejs
    branches: [temp/4.4]
  - url: https://github.com/couchbase/docs-sdk-php
    branches: [temp/4.2]
  - url: https://github.com/couchbase/docs-sdk-python
    branches: [temp/4.3]
  - url: https://github.com/couchbase/docs-sdk-ruby
    branches: [temp/3.5]
  - url: https://github.com/couchbase/docs-sdk-scala
    branches: [release/1.7]
  - url: https://github.com/couchbase/docs-sdk-extensions
    branches: [main]
    # Columnar dev
  - url: https://github.com/couchbase/docs-columnar-sdk-common
    branches: [release/1.0]
  - url: https://github.com/couchbase/docs-columnar-sdk-java
    branches: [release/1.0]
  - url: https://github.com/couchbase/docs-columnar-sdk-nodejs
    branches: [release/1.0]
  - url: https://github.com/couchbase/docs-columnar-sdk-python
    branches: [release/1.0]
    # Mobile Docs Pages
  - url: https://github.com/couchbase/docs-mobile
    branches: [release/3.1]
  - url: https://github.com/couchbaselabs/docs-couchbase-lite
    branches: [release/3.2]
  - url: https://github.com/couchbaselabs/docs-sync-gateway
    branches: [release/3.2]
  # - url: https://git@github.com/couchbase/docs-cloud-native
  - url: https://github.com/couchbase/docs-cloud-native
    branches: [cloud-native-2.2]
asciidoc:
  attributes:
    site-navigation-data-path: _/js/site-navigation-data.js
    enable-cmos: ''
    max-include-depth: 10
    page-partial: false
    experimental: ''
    idprefix: '@'
    idseparator: '-@'
    tabs: tabs
    tabs-sync-option: ''
    toc: ~
    page-toclevels: 1@
    page-rank: 50@
    xrefstyle: short
    enterprise: https://www.couchbase.com/products/editions[ENTERPRISE EDITION]
    community: https://www.couchbase.com/products/editions[COMMUNITY EDITION]
    sqlpp: SQL++
    sqlppc: SQL++ for Capella columnar
    sqlpp_url: https://www.couchbase.com/products/n1ql
    cbpp: Couchbase++
    kroki-server-url: http://3.91.133.254:9500
    kroki-fetch-diagram: true
  extensions:
  - ./lib/source-url-include-processor.js
  - ./lib/json-config-ui-block-macro.js
  - ./lib/inline-man-macro.js
  - ./lib/multirow-table-head-tree-processor.js
  - ./lib/swagger-ui-block-macro.js
  - ./lib/markdown-block.js
  - ./lib/template-block.js
  - asciidoctor-kroki
  - asciidoctor-external-callout
  - '@asciidoctor/tabs'
ui:
  bundle:
    url: https://github.com/couchbase/docs-ui/releases/download/prod-207/ui-bundle.zip
output:
  dir: ./public
runtime:
  fetch: true
