# This image extends the official Antora image to add bash and the aws command. It's used by the CI job.
FROM antora/antora:2.0.0

RUN apk add --no-cache --quiet bash ca-certificates python && \
    apk add --no-cache --quiet --virtual .build-deps py2-pip && \
    pip install --no-cache-dir --quiet --disable-pip-version-check awscli && \
    apk del --no-cache --quiet --purge .build-deps
