= Couchbase Docs Archive Site
:idprefix:
:idseparator: -
// Settings:
:hide-uri-scheme:
// URLs:
:url-docs: https://docs-archive.couchbase.com
:url-contribute: https://docs.couchbase.com/home/contribute/
:url-org: https://github.com/couchbase
:url-ui: {url-org}/docs-ui

This is the Antora playbook project (aka site build) for the Couchbase docs archive site published at {url-docs}.

== Prerequisites

You must have Node.js 16 installed to generate the site.

 node -v

If that command does not report a version that is 16 or greater, head over to https://nodejs.org to download the latest LTS release of Node.js.

== Playbook

The playbook, defined in the playbook file [.path]_antora-playbook.yml_, configures the build for this site.
The playbook specifies the content sources (repository and branches), site URL, UI bundle URL, global AsciiDoc attributes, and Asciidoctor extensions.

There's one playbook files in this repository:

antora-playbook.yml:: Configures the build for the *archive* site.

The archive site is built for each change to the archive branch.
A preview of the archive site is built for each pull request.

== Home Docs Component

The [.path]_home/_ directory in this repository contains the source for the Home documentation component.
All other content is sourced from separate repositories and branches.

== Custom Asciidoctor Extensions

The custom extensions in the [.path]_lib/_ directory process the manpage macro (Couchbase CLI and Backup components), Swagger UI macro, and multi-row table headers.

== Contributing

To learn how to use the playbook and generate the docs site locally, see our {url-contribute}[contributing guide].
