= Develop with Operational Insights
:page-layout: landing-page-top-level-sdk
:page-role: tiles
:page-rank: 75
:page-nav-header-levels: 1
:dotnet: .NET
:!sectids:
:table-caption!:
// :page-aliases: columnar-sdk.adoc

= Develop with Operational Insights

include::partial$info-banner.adoc[]

// xref:enterprise-analytics:intro:intro.adoc[Operational Insights] is a real-time analytical database (RT-OLAP) for real time apps and operational intelligence.
// Capella Columnar is a standalone, cloud-only offering from Couchbase under the Capella family of products.
// It uses column storage, which gives speedier retrieval of data.

[description]
xref:enterprise-analytics:intro:intro.adoc[Operational Insights] is a JSON-native NoSQL analytical database.
It serves to unify data from diverse sources, allowing for the execution of complex analytical queries and the extraction of timely insights.

{empty} +

* xref:enterprise-analytics:intro:intro.adoc[Operational Insights Enterprise] is a self-managed version of Couchbase's real-time analytical database (RT-OLAP), for running in your own datacenter or private cloud.
These pages cover the older Analytic SDKs, which are compatible with Operational Insights Enterprise 3.x. 
Unless you are in the process of migrating from an earlier Analytics project using these SDKs, you should instead look at our xref:operational-insights-sdk.adoc[Operational Insights SDKs] -- which will be developed to cover new functionality in future releases of Operational Insights.

* xref:analytics:intro:intro.adoc[Operational Insights Capella] is a Couchbase-managed version of our real-time analytical database (RT-OLAP), accessed through the Capella control plane, and running in your choice of CSP (AWS, Azure, or GCP).
Currently, xref:columnar-sdk.adoc[Columnar SDKs] must be used to connect to the Operational Insights Capella Service, as it presents a different connection interface, without Operational Insights Enterprise’s load balancer.


{empty} +


== SDK APIs to work with Operational Insights

TIP: This section covers Couchbase's older Analytics SDKs.
These have been superseded by the new xref:operational-insights-sdk.adoc[Operational Insights SDKs], and these Analytics SDKs will be deprecated in due course.

Analytics SDKs are developed from the ground-up and while they maintain some syntactic similarities with the xref:sdk.adoc[operational SDKs],
they are purpose built for Operational Insights' real-time analytical use cases.
They support streaming APIs to handle large datasets, as well as the common features expected to be present in any modern database SDK --
such as connection management and robust error handling.

[{tabs}] 
==== 

{dotnet}::
+
--
xref:dotnet-analytics-sdk:hello-world:overview.adoc[.NET Analytics SDK Docs] |
xref:dotnet-analytics-sdk:hello-world:start-using-sdk.adoc[Quickstart] |
https://docs.couchbase.com/sdk-api/analytics-dotnet-client[.NET Analytics API Reference]
--

Go::
+
--
xref:go-analytics-sdk:hello-world:overview.adoc[Go Analytics SDK Docs] |
xref:go-analytics-sdk:hello-world:start-using-sdk.adoc[Quickstart] |
https://pkg.go.dev/github.com/couchbase/gocbanalytics[Go API Reference]
--

Java::
+
--
xref:java-analytics-sdk:hello-world:overview.adoc[Java Analytics SDK Docs] |
xref:java-analytics-sdk:hello-world:start-using-sdk.adoc[Quickstart] |
https://docs.couchbase.com/sdk-api/couchbase-analytics-java-client/[Java API Reference]
--

Node.js::
+
--
xref:nodejs-analytics-sdk:hello-world:overview.adoc[Node.js Analytics SDK Docs] |  
xref:nodejs-analytics-sdk:hello-world:start-using-sdk.adoc[Quickstart] |
https://docs.couchbase.com/sdk-api/analytics-nodejs-client[Node.js API Reference]
--

Python::
+
--
xref:python-analytics-sdk:hello-world:overview.adoc[Python Analytics SDK Docs] |
xref:python-analytics-sdk:hello-world:start-using-sdk.adoc[Quickstart] |
https://docs.couchbase.com/sdk-api/analytics-python-client[Python API Reference]
--
====

{empty} +

=== Big Data Connectors

The available options for Operational Insights `DataFrame` and `Dataset` operations with the xref:spark-connector:ROOT:index.adoc[Couchbase Spark Connector]
can be found on the Spark xref:spark-connector:ROOT:spark-sql.adoc#enterprise-analytics-options[DataFrames, Datasets, and SQL] page.

See the xref:enterprise-analytics:sources:manage-remote.adoc[Operational Insights] docs for information on streaming from Confluent for Kafka.

{empty} +

== Analytics Offerings in Couchbase


.SDKs by analytics offering
|===
| Analytics offering | Development option

| xref:enterprise-analytics:intro:intro.adoc[Operational Insights Enterprise]
a|
* xref:operational-insights-sdk.adoc[Insights SDKs]
* xref:analytics-sdk.adoc[Analytics SDKs]


| xref:analytics:intro:intro.adoc[Operational Insights Capella]
| xref:columnar-sdk.adoc[Columnar SDKs]

| xref:server:learn:services-and-indexes/services/analytics-service.adoc[Analytics Service (CBAS)] 
| xref:sdk.adoc[Operational SDKs]
|===



In addition to Operational Insights Enterprise Clusters,
// (self-managed and Capella Analytics), 
older Operational Insights is also available as a managed service --
Operational Insights Capella, formerly Columnar.

Traditional, row-based analytics is also available in Couchbase operational clusters -- self-managed, or Capella Operational.


{empty} +

=== SDK APIs to work with Operational Insights Capella:

xref:analytics:intro:intro.adoc[Operational Insights Capella] is a standalone, managed cloud offering from Couchbase under the Capella family of products.

Operational Insights Capella SDKs, formerly known as Columnar SDKs, are similar to the Operational Insights SDKs.
They must be used to connect to the current Operational Insights Capella Service, as it presents a different connection interface, without Operational Insights Enterprise's load balancer.

[{tabs}] 
==== 
Go::
+
--
xref:go-columnar-sdk:hello-world:overview.adoc[Go Columnar SDK Docs] |
xref:go-columnar-sdk:hello-world:start-using-sdk.adoc[Quickstart] |
https://pkg.go.dev/github.com/couchbase/gocbcolumnar[Go API Reference]
--

Java::
+
--
xref:java-columnar-sdk:hello-world:overview.adoc[Java Columnar SDK Docs] |
xref:java-columnar-sdk:hello-world:start-using-sdk.adoc[Quickstart] |
https://docs.couchbase.com/sdk-api/couchbase-columnar-java-client[Java API Reference]
--

Node.js::
+
--
xref:nodejs-columnar-sdk:hello-world:overview.adoc[Node.js Columnar SDK Docs] |  
xref:nodejs-columnar-sdk:hello-world:start-using-sdk.adoc[Quickstart] |
https://docs.couchbase.com/sdk-api/columnar-nodejs-client[Node.js API Reference]
--

Python::
+
--
xref:python-columnar-sdk:hello-world:overview.adoc[Python Columnar SDK Docs] |
xref:python-columnar-sdk:hello-world:start-using-sdk.adoc[Quickstart] |
https://docs.couchbase.com/sdk-api/columnar-python-client[Python API Reference]
--
====


{empty} +

=== Row-Based Couchbase Analytics

xref:server:learn:services-and-indexes/services/analytics-service.adoc[CBAS (Couchbase Analytics Service)] is our classic OLAP available as part of self-managed Couchbase Server and Capella Operational.
Use the xref:sdk.adoc[operational SDKs] to develop for this service.
