= Develop with Capella Analytics 
:page-layout: landing-page-top-level-sdk
:page-role: tiles
:page-rank: 75
:!sectids:

= Develop with Capella Analytics 

include::partial$info-banner.adoc[]

xref:analytics:intro:intro.adoc[Capella Analytics] is a real-time analytical database (RT-OLAP) for real time apps and operational intelligence.
Capella Analytics is a standalone, cloud-only offering from Couchbase under the Capella family of products.

TIP
.Which Analytics Service?
====
Capella Analytics and Enterprise Analytics are column-based real-time analytical databases.

Capella Analytics SDKs, also known as Columnar SDKs, are similar to the Enterprise Analytics SDKs.
They must be used to connect to the current Capella Analytics Service, as it presents a different connection interface, without Enterprise Analytics' load balancer.

To connect to self-managed Enterprise Analytics, use our xref:analytics-sdk.adoc[Enterprise Analytics SDKs].

xref:server:learn:services-and-indexes/services/analytics-service.adoc[CBAS (Couchbase Analytics Service)] is our classic OLAP available as part of self-managed Couchbase Server and Capella Operational.
Use the xref:sdk.adoc[operational SDKs] to develop for this service.
====


== SDK APIs to work with Capella Analytics:

Columnar SDKs are developed from the ground-up and while they maintain some syntactic similarities with the xref:sdk.adoc[operational SDKs],
they are purpose built for Capella Analytics's real-time analytical use cases.
They support streaming APIs to handle large datasets, as well as the common features expected to be present in any modern database SDK --
such as connection management and robust error handling.


[{tabs}] 
==== 
Go::
+
--
xref:go-columnar-sdk:hello-world:overview.adoc[Go Columnar SDK Docs] |
xref:go-columnar-sdk:hello-world:start-using-sdk.adoc[Quickstart] |
https://pkg.go.dev/github.com/couchbase/gocbcolumnar[Go API Reference]
--

Java::
+
--
xref:java-columnar-sdk:hello-world:overview.adoc[Java Columnar SDK Docs] |
xref:java-columnar-sdk:hello-world:start-using-sdk.adoc[Quickstart] |
https://docs.couchbase.com/sdk-api/couchbase-columnar-java-client[Java API Reference]
--

Node.js::
+
--
xref:nodejs-columnar-sdk:hello-world:overview.adoc[Node.js Columnar SDK Docs] |  
xref:nodejs-columnar-sdk:hello-world:start-using-sdk.adoc[Quickstart] |
https://docs.couchbase.com/sdk-api/columnar-nodejs-client[Node.js API Reference]
--

Python::
+
--
xref:python-columnar-sdk:hello-world:overview.adoc[Python Columnar SDK Docs] |
xref:python-columnar-sdk:hello-world:start-using-sdk.adoc[Quickstart] |
https://docs.couchbase.com/sdk-api/columnar-python-client[Python API Reference]
--
====


