= Develop with Operational Insights Capella 
:page-layout: landing-page-top-level-sdk
:page-role: tiles
:page-rank: 75
:!sectids:

= Develop with Operational Insights Capella

include::partial$info-banner.adoc[]

[description]
xref:analytics:intro:intro.adoc[Operational Insights Capella] is a real-time analytical database (RT-OLAP) for real time apps and operational intelligence.
Operational Insights Capella is a standalone, managed offering from Couchbase under the Capella family of products --
a self-managed xref:enterprise-analytics:intro:intro.adoc[Operational Insights Enterprise] product is also available.

[TIP]
.Which Analytics Service?
====
Operational Insights Capella and Operational Insights Enterprise are column-based real-time analytical databases.

Operational Insights Capella SDKs, also known as Columnar SDKs, are similar to the Operational Insights Enterprise SDKs.
They must be used to connect to the current Operational Insights Capella Service, as it presents a different connection interface, without Operational Insights Enterprise's load balancer.

To connect to self-managed Operational Insights Enterprise, use our xref:operational-insights-sdk.adoc[Operational Insights SDKs].

xref:server:learn:services-and-indexes/services/analytics-service.adoc[Analytics Service (CBAS)] is our classic OLAP available as part of self-managed Couchbase Server and Capella Operational.
Use the xref:sdk.adoc[operational SDKs] to develop for this service.
====


== SDK APIs to work with Operational Insights Capella:

Columnar SDKs are developed from the ground-up and while they maintain some syntactic similarities with the xref:sdk.adoc[operational SDKs],
they are purpose built for Operational Insights Capella's real-time analytical use cases.
They support streaming APIs to handle large datasets, as well as the common features expected to be present in any modern database SDK --
such as connection management and robust error handling.


[{tabs}] 
==== 
Go::
+
--
xref:go-columnar-sdk:hello-world:overview.adoc[Go Columnar SDK Docs] |
xref:go-columnar-sdk:hello-world:start-using-sdk.adoc[Quickstart] |
https://pkg.go.dev/github.com/couchbase/gocbcolumnar[Go API Reference]
--

Java::
+
--
xref:java-columnar-sdk:hello-world:overview.adoc[Java Columnar SDK Docs] |
xref:java-columnar-sdk:hello-world:start-using-sdk.adoc[Quickstart] |
https://docs.couchbase.com/sdk-api/couchbase-columnar-java-client[Java API Reference]
--

Node.js::
+
--
xref:nodejs-columnar-sdk:hello-world:overview.adoc[Node.js Columnar SDK Docs] |  
xref:nodejs-columnar-sdk:hello-world:start-using-sdk.adoc[Quickstart] |
https://docs.couchbase.com/sdk-api/columnar-nodejs-client[Node.js API Reference]
--

Python::
+
--
xref:python-columnar-sdk:hello-world:overview.adoc[Python Columnar SDK Docs] |
xref:python-columnar-sdk:hello-world:start-using-sdk.adoc[Quickstart] |
https://docs.couchbase.com/sdk-api/columnar-python-client[Python API Reference]
--
====


