= Develop with Capella Columnar 
:page-layout: landing-page-top-level-sdk
:page-role: tiles
:page-rank: 75
:!sectids:

= Develop with Capella Columnar 

include::partial$info-banner.adoc[]

xref:columnar:intro:intro.adoc[Capella Columnar] is a real-time analytical database (RT-OLAP) for real time apps and operational intelligence.
Capella Columnar is a standalone, cloud-only offering from Couchbase under the Capella family of products.

Columnar SDKs are developed from the ground-up and while they maintain some syntactic similarities with the xref:sdk.adoc[operational SDKs],
they are purpose built for Columnar's analytical use cases.
They support streaming APIs to handle large datasets, as well as the common features expected to be present in any modern database SDK --
such as connection management and robust error handling.

== SDK APIs to work with Capella Columnar:


[{tabs}] 
==== 
Go::
+
--
xref:go-columnar-sdk:hello-world:overview.adoc[Go Columnar SDK Docs] |
xref:go-columnar-sdk:hello-world:start-using-sdk.adoc[Quickstart] |
https://pkg.go.dev/github.com/couchbase/gocbcolumnar[Go API Reference]
--

Java::
+
--
xref:java-columnar-sdk:hello-world:overview.adoc[Java Columnar SDK Docs] |
xref:java-columnar-sdk:hello-world:start-using-sdk.adoc[Quickstart] |
https://docs.couchbase.com/sdk-api/columnar-java-client[Java API Reference]
--

Node.js::
+
--
xref:nodejs-columnar-sdk:hello-world:overview.adoc[Node.js Columnar SDK Docs] |  
xref:nodejs-columnar-sdk:hello-world:start-using-sdk.adoc[Quickstart] |
https://docs.couchbase.com/sdk-api/columnar-nodejs-client[Node.js API Reference]
--

Python::
+
--
xref:python-columnar-sdk:hello-world:overview.adoc[Python Columnar SDK Docs] |
xref:python-columnar-sdk:hello-world:start-using-sdk.adoc[Quickstart] |
https://docs.couchbase.com/sdk-api/columnar-python-client[Python API Reference]
--
====


