= Couchbase Documentation
:page-layout: landing-page-capella
:page-rank: 75
:!sectids:
:table-caption!:



include::partial$info-banner.adoc[]



= Couchbase Documentation

The Developer Data Platform for Critical Applications in Our AI World.

Couchbase is a multipurpose NoSQL database for transactional, analytical, mobile, and AI applications.
Our operational and analytical databases can be deployed self-managed or fully-managed as a service offering.
Offline-first mobile takes Couchbase to the edge, and can be synced via App Services in the cloud, or a self-managed Sync Gateway deployment.
AI Services (currently in private preview) simplify building agentic apps.

Most services are available to run self-managed in your datacenter, or managed by Couchbase in the Capella family of products.


[.centered.card-container]
== A Multipurpose NoSQL Platform for Transactional, Analytical, Mobile / Edge, and AI Applications

[.card-box]
=== icon:rocket[] Transactional Workloads -- in the Cloud or your Datacenter

Explore {sqlpp}, or the fast CRUD interface of the Data Service.

* Capella Operational -- 
** https://cloud.couchbase.com/sign-up[Sign Up to Capella^]
** xref:cloud:get-started:intro.adoc[Read the Capella Docs]
**  xref:~@develop:develop:intro.adoc[Develop for Capella]
* Self-managed xref:server:getting-started:start-here.adoc[Couchbase Server]
** xref:operator::overview.adoc[Couchbase Autonomous Operator for Kubernetes]
** xref:7.6@develop:develop:intro.adoc[Develop for Couchbase Server]
* xref:sdk.adoc[Operational SDKs]


[.card-box]
=== icon:rocket[] Real Time Analytics with Analytics SDKs

Enterprise Analytics brings the power of NoSQL to the world of analytics -- self-managed, or in Capella.

* xref:enterprise-analytics:intro:intro.adoc[Enterprise Analytics]
** xref:home::analytics-sdk.adoc[Enterprise Analytics SDK pages]
* xref:analytics:intro:intro.adoc[Capella Analytics] 
** xref:home::columnar-sdk.adoc[Capella Analytics SDK pages]
* xref:server:analytics:introduction.adoc[CBAS] -- traditional row-based analytics in the operational database
** xref:java-sdk:howtos:analytics-using-sdk.adoc[CBAS from the SDK]


[.card-box]
=== icon:rocket[] Develop for Mobile and the Edge

Build your app in Couchbase Lite (CBL) for offline-first connectivity, then sync to Couchbase Server with Capella App services (or self-managed Sync Gateway) -- or run peer-to-peer.


* Couchbase Lite for xref:couchbase-lite:android:quickstart.adoc[Android in Java or Kotlin] |
* xref:couchbase-lite:swift:quickstart.adoc[iOS Swift]
and xref:couchbase-lite:objc:quickstart.adoc[iOS Objective-C] |
xref:couchbase-lite:c:quickstart.adoc[Edge devices in C] |
xref:couchbase-lite:csharp:quickstart.adoc[C# .NET] | 
xref:couchbase-lite:java:quickstart.adoc[Java] | 
xref:couchbase-lite:javascript:quickstart.adoc[JavaScript -- Ionic and React]
* Sync your data with:
** xref:cloud:mobile-guides:intro.adoc[Capella App Services]
** self-managed SyncGateway 
** Edge Server 
** peer-to-peer.


[.card-box]
=== icon:rocket[] Develop RAG and Agentic AI Applications

Vector Query  facilitates RAG applications speedily and at scale. 
Vector Search Service offers the ability to combine searches with our sophisticated Search API.

Agentic Apps can be built with Agent Catalog (https://info.couchbase.com/capella-ai-services-signup[currently in Private Preview]).




[.column]
====== {empty}

== Explore Products and Services

Self-managed in your data center or private cloud -- or Couchbase-managed with Capella services -- the choice is yours.


[.column]
====== {empty}

.Capella -- Couchbase-Managed Deployment

[#table_products-services,cols="25,25,25,25"]
|===
| Operational | Real-Time Analytics | Mobile | AI Services

a| xref:cloud::index.adoc[Couchbase Capella]

a| xref:columnar:intro:intro.adoc[Capella Analytics]

a| xref:xref:cloud:mobile-guides:intro.adoc[Capella App Services]

a| https://info.couchbase.com/capella-ai-services-signup[AI Services Private Preview]
|===





[.column]
====== {empty}

[.column]
====== {empty}


.Self-Managed Couchbase Server Deployment

[#table_products-services,cols="25,25,25,25"]
|===
| Operational | Real-Time Analytics | Mobile | Working with LLMs

a| * xref:server.adoc[Couchbase Server]
* xref:operator::overview.adoc[Couchbase Autonomous Operator]
* Connectors.....

a| * xref:enterprise-analytics:intro:intro.adoc[Enterprise Analytics]
* Connectors.....

a| xref:sync-gateway::index.adoc[Couchbase Sync Gateway]

a| Vector search for RAG
|===





[.column]
====== {empty}


.The Couchbase Developer Story

[#table_products-services,cols="25,25,25,25"]
|===
| Operational | Real-Time Analytics | Mobile | AI Services

a| Develop against Capella Operational _and_ self-managed Couchbase Server,
with xref:sdk.adoc[SDKs] in eleven popular programming languages.
+
Connectors.....

a| 
* xref:columnar-sdk.adoc[Capella Analytics SDKs] 
* xref:analytics-sdk.adoc[Enterprise Analytics SDKs] 
* Connectors.....

a| 
* xref:couchbase-lite:android:quickstart.adoc[Develop for Android in Java or Kotlin]
* xref:couchbase-lite:swift:quickstart.adoc[Develop for iOS on Swift]
(and xref:couchbase-lite:objc:quickstart.adoc[Objective-C])
* xref:couchbase-lite:c:quickstart.adoc[Devlop for Edge devices in C]
* Couchbase Lite xref:couchbase-lite:csharp:quickstart.adoc[on C# .NET] | 
xref:couchbase-lite:java:quickstart.adoc[Java] | 
xref:couchbase-lite:javascript:quickstart.adoc[JavaScript -- Ionic and React]

a| * Agentic Apps can be built with Agent Catalog (currently in Private Preview)
* Vector search for RAG
|===






[.column]
====== {empty}


[.column]
====== {empty}

== More Developer Resources
++++
<div class="card-row three-column-row">
++++

[.column]
====== {empty}
.Developer Portal

[.content]
Explore a variety of resources - sample apps, videos, blogs, and more, to build applications using Couchbase.

https://developer.couchbase.com[Developer Portal]
https://developer.couchbase.com/tutorials[Developer Tutorials]


[.column]
====== {empty}
.Academy

[.content]
Explore extensive hands-on learning experiences through free, online courses or under the guidance of an in-person instructor.

https://learn.couchbase.com/store[Academy]

[.column]
====== {empty}
.Community

[.content]
With open source roots, Couchbase has a rich history of collaboration and community. Connect with our developer community and get involved.

https://forums.couchbase.com/[Community]

++++
</div>
++++



[.column]
====== {empty}

== Feedback and Contributions

++++
<div class="card-row three-column-row">
++++

[.column]
====== {empty}
.Provide Feedback

[.content]
Provide feedback, and get help with any problem you may encounter.

xref:server:introduction:contact-couchbase.adoc[Provide Feedback]


[.column]
====== {empty}
.Contact Support

[.content]
Couchbase Support provides online support for customers of Enterprise Edition who have a support contract.

xref:server:introduction:contact-couchbase.adoc[Contact Couchbase]

[.column]
====== {empty}
.Contribute

[.content]
You can submit simple changes, such as typo fixes and minor clarifications directly on GitHub. Contributions are greatly encouraged.

xref:home:contribute:index.adoc[Contribute to the Documentation]

++++
</div>
++++

