= Couchbase Documentation
:page-meta-zd-site-verification: odvin2siwmodz30xrtxq
:page-layout: landing-page-top-level-sdk
:page-role: tiles
:page-rank: 75
:!sectids:
:collapsible:


include::partial$info-banner.adoc[]



= Couchbase Documentation

The Developer Data Platform for Critical Applications in Our AI World.

Couchbase is a multipurpose NoSQL database for transactional, analytical, mobile, and AI applications.
Our operational and analytical databases can be deployed self-managed or fully-managed as a service offering.
Offline-first mobile takes Couchbase to the edge, and can be synced via App Services in the cloud, or a self-managed Sync Gateway deployment.
AI Services (currently in private preview) simplify building agentic apps.


[.centered.card-container]
== A Multipurpose NoSQL Platform for Transactional, Analytical, Mobile / Edge, and AI Applications

[.card-box]
=== icon:rocket[] Transactional Workloads -- in the Cloud or your Datacenter

Develop an app for xref:capella@develop:develop:intro.adoc[Capella Operational],
or a xref:7.6@develop:develop:intro.adoc[self-managed Couchbase Server].
Explore {sqlpp}, or the fast CRUD interface of the Data Service.

* xref:java-sdk:hello-world:start-using-sdk.adoc[Get Started with the Java SDK]
* xref:server/current/tutorials/couchbase-tutorial-student-records.adoc[NoSQL for RDBMS users]
* Try our xref:sdk.adoc[other SDKs]:
+
xref:c-sdk:hello-world:overview.adoc[C]
| xref:cxx-sdk:hello-world:overview.adoc[{cpp}]
| xref:dotnet-sdk:hello-world:overview.adoc[.NET]
| xref:go-sdk:hello-world:overview.adoc[Go]
| xref:kotlin-sdk:hello-world:overview.adoc[Kotlin]
| xref:nodejs-sdk:hello-world:overview.adoc[Node.js]
| xref:php-sdk:hello-world:overview.adoc[PHP]
| xref:python-sdk:hello-world:overview.adoc[Python]
| xref:ruby-sdk:hello-world:overview.adoc[Ruby]
| xref:scala-sdk:hello-world:overview.adoc[Scala]
* xref:cloud:third-party:integrations.adoc[Integrations, Connectors, and Tools]
// * Multi-Document ACID Transactions
// * xref:cloud:develop:intro.adoc[Capella Operational Developer Intro]


[.card-box]
=== icon:rocket[] Real Time Analytics with Analytics SDKs

xref:columnar:intro:intro.adoc[Enterprise Analytics] brings the power of NoSQL to the world of analytics.
Self-managed Enterprise Analytics brings real-time adaptive applications to your datacenter or private cloud --
or try this service fully-hosted as Capella Columnar, which integrates seamlessly with the Couchbase Capella cloud platform.
// Or try self-managed Enterprise Analytics, in your datacenter or private cloud.

////
xref:columnar-sdk.adoc[Columnar SDKs] are developed from the ground-up and while they maintain some syntactic similarities with the xref:sdk.adoc[operational SDKs],
they are purpose built for Enterprise Analytics' analytical use cases.
They support streaming APIs to handle large datasets, as well as the common features expected to be present in any modern database SDK --
such as connection management and robust error handling.
////

* xref:go-columnar-sdk:hello-world:overview.adoc[Go Analytics SDK Docs]
* xref:java-columnar-sdk:hello-world:overview.adoc[Java Analytics SDK Docs]
* xref:nodejs-columnar-sdk:hello-world:overview.adoc[Node.js Analytics SDK Docs]
* xref:python-columnar-sdk:hello-world:overview.adoc[Python Analytics SDK Docs] 



[.card-box]
=== icon:rocket[] Develop for Mobile and the Edge

Build your app for offline-first connectivity, then sync to Couchbase Server with Capella App services (or self-managed Sync Gateway) -- or run peer-to-peer.


* xref:couchbase-lite:android:quickstart.adoc[Develop for Android in Java or Kotlin]
* xref:couchbase-lite:swift:quickstart.adoc[Develop for iOS on Swift]
(and xref:couchbase-lite:objc:quickstart.adoc[Objective-C])
* xref:couchbase-lite:c:quickstart.adoc[Devlop for Edge devices in C]
* Couchbase Lite xref:couchbase-lite:csharp:quickstart.adoc[on C# .NET] | 
xref:couchbase-lite:java:quickstart.adoc[Java] | 
xref:couchbase-lite:javascript:quickstart.adoc[JavaScript -- Ionic and React]
* Sync your data with App Services / self-managed SyncGateway / Edge Server -- or run peer-to-peer.


[.card-box]
=== icon:rocket[] Develop RAG and Agentic AI Applications

Our Vector Search Service facilitates RAG applications -- and offers the ability to combine searches with our sophisticated Search API.
Agentic Apps can be built with Agent Catalog (currently in Private Preview), and our Vector Search Service enables RAG, to side-step AI hallucinations.








[.column]
====== {empty}

== Explore Products and Services

Self-managed in your data center or private cloud -- or Couchbase-managed with Capella services -- the choice is yours.


=== Capella -- Couchbase-Managed Deployment

[#table_products-services,cols="25,25,25,25"]
|===
| Operational | Real-Time Analytics | Mobile | AI Services

a| xref:cloud::index.adoc[Couchbase Capella]

a| xref:columnar:intro:intro.adoc[Capella Analytics]

a| xref:xref:cloud:mobile-guides:intro.adoc[Capella App Services]

a| https://info.couchbase.com/capella-ai-services-signup[AI Services Private Preview]
|===





[.column]
====== {empty}


=== Self-Managed Couchbase Server Deployment

[#table_products-services,cols="25,25,25,25"]
|===
| Operational | Real-Time Analytics | Mobile | Working with LLMs

a| xref:server.adoc[Couchbase Server]
* xref:operator::overview.adoc[Couchbase Autonomous Operator]
* Connectors.....

a| xref:enterprise-analytics:intro:intro.adoc[Enterprise Analytics]
Connectors.....

a| xref:sync-gateway::index.adoc[Couchbase Sync Gateway]

a| Vector search for RAG
|===





[.column]
====== {empty}


=== The Couchbase Developer Story

[#table_products-services,cols="25,25,25,25"]
|===
| Operational | Real-Time Analytics | Mobile | AI Services

a| Develop against Capella Operational _and_ self-managed Couchbase Server,
with xref:sdk.adoc[SDKs] in eleven popular programming languages.
Connectors.....

a| 
* xref:columnar-sdk.adoc[Capella Analytics SDKs] 
* xref:analytics-sdk.adoc[Enterprise Analytics SDKs] 
* Connectors.....

a| 
* xref:couchbase-lite:android:quickstart.adoc[Develop for Android in Java or Kotlin]
* xref:couchbase-lite:swift:quickstart.adoc[Develop for iOS on Swift]
(and xref:couchbase-lite:objc:quickstart.adoc[Objective-C])
* xref:couchbase-lite:c:quickstart.adoc[Devlop for Edge devices in C]
* Couchbase Lite xref:couchbase-lite:csharp:quickstart.adoc[on C# .NET] | 
xref:couchbase-lite:java:quickstart.adoc[Java] | 
xref:couchbase-lite:javascript:quickstart.adoc[JavaScript -- Ionic and React]

a| * Agentic Apps can be built with Agent Catalog (currently in Private Preview)
* Vector search for RAG
|===







[.column]
====== {empty}

== More Developer Resources
++++
<div class="card-row three-column-row">
++++

[.column]
====== {empty}
.Developer Portal

[.content]
Explore a variety of resources - sample apps, videos, blogs, and more, to build applications using Couchbase.

https://developer.couchbase.com[Developer Portal]
https://developer.couchbase.com/tutorials[Developer Tutorials]


[.column]
====== {empty}
.Academy

[.content]
Explore extensive hands-on learning experiences through free, online courses or under the guidance of an in-person instructor.

https://learn.couchbase.com/store[Academy]

[.column]
====== {empty}
.Community

[.content]
With open source roots, Couchbase has a rich history of collaboration and community. Connect with our developer community and get involved.

https://forums.couchbase.com/[Community]

++++
</div>
++++



[.column]
====== {empty}

== Feedback and Contributions

++++
<div class="card-row three-column-row">
++++

[.column]
====== {empty}
.Provide Feedback

[.content]
Provide feedback, and get help with any problem you may encounter.

xref:server:introduction:contact-couchbase.adoc[Provide Feedback]


[.column]
====== {empty}
.Contact Support

[.content]
Couchbase Support provides online support for customers of Enterprise Edition who have a support contract.

xref:server:introduction:contact-couchbase.adoc[Contact Couchbase]

[.column]
====== {empty}
.Contribute

[.content]
You can submit simple changes, such as typo fixes and minor clarifications directly on GitHub. Contributions are greatly encouraged.

xref:home:contribute:index.adoc[Contribute to the Documentation]

++++
</div>
++++

