= Couchbase Documentation
:page-meta-zd-site-verification: odvin2siwmodz30xrtxq
:page-layout: landing-page-top-level-sdk
:page-role: tiles
:page-rank: 75
:!sectids:
:collapsible:

include::partial$info-banner.adoc[]

= Couchbase Documentation

++++
<div class="card-row">
++++

[.column]
====== {empty}
[.content]
_Couchbase is the modern database for enterprise applications._

Couchbase is a distributed document database with a powerful search engine and in-built operational and analytical capabilities. It brings the power of NoSQL to the edge and provides fast, efficient bidirectional synchronization of data between the edge and the cloud.

Find the documentation, samples, and references to help you use Couchbase and build applications.

[.column]
====== {empty}
[.content]
----
// List the schedule of flights from Boston
// to San Francisco on JETBLUE

SELECT DISTINCT airline.name, route.schedule
FROM `travel-sample`.inventory.route
  JOIN `travel-sample`.inventory.airline
  ON KEYS route.airlineid
WHERE route.sourceairport = "BOS"
AND route.destinationairport = "SFO"
AND airline.callsign = "JETBLUE";
----

++++
</div>
++++

[.column]
====== {empty}

== Get Started
++++
<div class="card-row three-column-row">
++++

[.column]
====== {empty}
.Couchbase Capella (DBaaS)

[.content]
Explore Couchbase Capella, our fully-managed database as a service offering.
Take the complexity out of deploying, managing, scaling, and securing Couchbase in the public cloud. 
Store, query, and analyze any amount of data -- and let us handle more of the administration -- all in a few clicks. 

xref:cloud::index.adoc[Couchbase Capella]

{empty} +

.Capella Analytics (RT-OLAP)

Capella Analytics is a real-time analytical database (RT-OLAP) for real time apps and operational intelligence.
Capella Analytics is a standalone, cloud-only offering from Couchbase under the Capella family of products.

xref:analytics:intro:intro.adoc[Capella Analytics]


[.column]
====== {empty}
.Couchbase Server

[.content]
Explore Couchbase Server, a modern, distributed document database with all the desired capabilities of a relational database and more. It exposes a scale-out, key-value store with managed cache for sub-millisecond data operations, purpose-built indexers for efficient queries, and a powerful query engine for executing SQL-like queries.

xref:server.adoc[Couchbase Server]

{empty} +

.Enterprise Analytics (RT-OLAP)

Enterprise Analytics is a self-managed analytical database (RT-OLAP) for real time apps and operational intelligence.

xref:enterprise-analytics:intro:intro.adoc[Enterprise Analytics]

[.column]
====== {empty}
.Couchbase Mobile

[.content]
_Couchbase Mobile_ brings the power of NoSQL to the edge.
The combination of _Sync Gateway_ and _Couchbase Lite_ coupled with the power of _Couchbase Server_ provides fast, efficient bidirectional synchronization of data between the edge and the cloud.
Enabling you to deploy your offline-first mobile and embedded applications with greater agility on premises or in any cloud.

xref:couchbase-lite::introduction.adoc[Couchbase Lite] |
xref:sync-gateway::introduction.adoc[Sync Gateway] |
xref:couchbase-edge-server:introduction:intro.adoc[Couchbase Edge Server]

{empty} +

.Capella AI Services

[.content]
Capella AI Services is a fully managed set of tools that help you build, deploy, and scale your agentic and retrieval-augmented generation (RAG) AI applications.
These tools integrate seamlessly with the Couchbase Capella cloud platform, enabling you to develop your AI applications on the same platform as your data.

xref:ai:get-started:intro.adoc[Capella AI Services]

++++
</div>
++++

[.column]
====== {empty}

== Developer Tools
++++
<div class="card-row three-column-row">
++++

[.column]
====== {empty}
.SDK and Connectors

[.content]
Couchbase SDKs allow applications to access a Couchbase cluster and the big data Connectors enable data exchange with other platforms.

xref:home:ROOT:developer.adoc[Developer Docs] |
xref:home:ROOT:sdk.adoc[Operational SDKs] |
xref:home:ROOT:analytics-sdk.adoc[Enterprise Analytics SDKs] |
xref:home:ROOT:columnar-sdk.adoc[Capella Analytics SDKs]

[.column]
====== {empty}
.CLI and REST APIs

[.content]
Use the command-line interface (CLI) tools and REST API to manage and monitor your Couchbase deployment.

xref:server:cli:cli-intro.adoc[Couchbase CLI] | xref:server:rest-api:rest-intro.adoc[REST API]

[.column]
====== {empty}
.Couchbase Shell

[.content]
A modern shell to interact with Couchbase Server and Capella, now available.

https://couchbase.sh[Explore Couchbase Shell]

++++
</div>
++++

[.column]
====== {empty}

== More Developer Resources
++++
<div class="card-row three-column-row">
++++

[.column]
====== {empty}
.Developer Portal

[.content]
Explore a variety of resources - sample apps, videos, blogs, and more, to build applications using Couchbase.

https://developer.couchbase.com[Developer Portal]
https://developer.couchbase.com/tutorials[Developer Tutorials]


[.column]
====== {empty}
.Academy

[.content]
Explore extensive hands-on learning experiences through free, online courses or under the guidance of an in-person instructor.

https://learn.couchbase.com/store[Academy]

[.column]
====== {empty}
.Community

[.content]
With open source roots, Couchbase has a rich history of collaboration and community. Connect with our developer community and get involved.

https://forums.couchbase.com/[Community]

++++
</div>
++++

[.column]
====== {empty}

== Explore Products and Services

[#table_products-services,cols="25,25,25,25"]
|===
| Cloud | Server | SDK and Connectors | Mobile

a| xref:cloud::index.adoc[Couchbase Capella]

xref:analytics:intro:intro.adoc[Capella Analytics]




a| xref:server.adoc[Couchbase Server]

xref:enterprise-analytics:intro:intro.adoc[Enterprise Analytics]

xref:operator::overview.adoc[Couchbase Autonomous Operator]

xref:service-broker::index.adoc[Couchbase Service Broker]

xref:cmos::index.adoc[Couchbase Monitoring and Observability Stack]





a| xref:java-sdk:hello-world:overview.adoc[Couchbase Java SDK]

xref:scala-sdk:hello-world:overview.adoc[Couchbase Scala SDK]

xref:dotnet-sdk:hello-world:overview.adoc[Couchbase .NET SDK]

xref:cxx-sdk:hello-world:overview.adoc[Couchbase {cpp} SDK]

xref:c-sdk:hello-world:overview.adoc[Couchbase C SDK]

xref:nodejs-sdk:hello-world:overview.adoc[Couchbase Node.js SDK]

xref:php-sdk:hello-world:overview.adoc[Couchbase PHP SDK]

xref:python-sdk:hello-world:overview.adoc[Couchbase Python SDK]

xref:ruby-sdk:hello-world:overview.adoc[Couchbase Ruby SDK]

xref:go-sdk:hello-world:overview.adoc[Couchbase Go SDK]

xref:kotlin-sdk:hello-world:overview.adoc[Couchbase Kotlin SDK]

xref:elasticsearch-connector::getting-started.adoc[Couchbase Elasticsearch Connector]

xref:kafka-connector::quickstart.adoc[Couchbase Kafka Connector]

xref:spark-connector::getting-started.adoc[Couchbase Spark Connector]

xref:go-analytics-sdk:hello-world:overview.adoc[Go Analytics SDK]

xref:java-analytics-sdk:hello-world:overview.adoc[Java Analytics SDK]

xref:nodejs-analytics-sdk:hello-world:overview.adoc[Node.js Analytics SDK]

xref:python-analytics-sdk:hello-world:overview.adoc[Python Analytics SDK]

xref:go-columnar-sdk:hello-world:overview.adoc[Go Columnar SDK]

xref:java-columnar-sdk:hello-world:overview.adoc[Java Columnar SDK]

xref:nodejs-columnar-sdk:hello-world:overview.adoc[Node.js Columnar SDK]

xref:python-columnar-sdk:hello-world:overview.adoc[Python Columnar SDK]

a| xref:couchbase-lite:javascript:quickstart.adoc[Couchbase Lite JavaScript]

xref:couchbase-lite:csharp:quickstart.adoc[Couchbase Lite C#]

xref:couchbase-lite:java:quickstart.adoc[Couchbase Lite Java]

xref:couchbase-lite:android:quickstart.adoc[Couchbase Lite Java Android]

xref:couchbase-lite:swift:quickstart.adoc[Couchbase Lite Swift]

xref:couchbase-lite:objc:quickstart.adoc[Couchbase Lite Objective-C]

xref:sync-gateway::index.adoc[Couchbase Sync Gateway]
|===

[.column]
====== {empty}

== Feedback and Contributions

++++
<div class="card-row three-column-row">
++++

[.column]
====== {empty}
.Provide Feedback

[.content]
Provide feedback, and get help with any problem you may encounter.

xref:server:introduction:contact-couchbase.adoc[Provide Feedback]


[.column]
====== {empty}
.Contact Support

[.content]
Couchbase Support provides online support for customers of Enterprise Edition who have a support contract.

xref:server:introduction:contact-couchbase.adoc[Contact Couchbase]

[.column]
====== {empty}
.Contribute

[.content]
You can submit simple changes, such as typo fixes and minor clarifications directly on GitHub. Contributions are greatly encouraged.

xref:home:contribute:index.adoc[Contribute to the Documentation]

++++
</div>
++++
