= Couchbase Mobile - Embedded Database on the Edge
:page-layout: landing-page-core-concept
:page-role: tiles
:!sectids:

= Couchbase for Mobile/Edge
++++
<div class="card-row">
++++

[.column]
====== {empty}
[.content]
Bring the power of NoSQL to the edge with Sync Gateway and Couchbase Lite. Combined with Couchbase Server, it provides fast, efficient bidirectional synchronization of data between the edge and the cloud. Enabling you to deploy your offline-first mobile and embedded applications with greater agility on premises or in any cloud.

[.column]
====== {empty}
[.media-left]
image::secure-manage-and-develop-with-ease.svg[,300]

++++
</div>
++++

== Embedded Database on the Edge
++++
<div class="card-row three-column-row">
++++

[.column]
.Couchbase Lite

[.content]
Couchbase Lite is an embedded, NoSQL JSON Document Style database for your mobile apps. It natively supports all major operating systems and platforms. Its NoSQL client database provides CRUD, full-text search and query capabilities that runs locally on the device.
{empty}
xref:couchbase-lite::introduction.adoc[Go to Couchbase Lite Docs]

[.column]
.Sync Gateway

[.content]
Sync Gatway is an internet-facing synchronization mechanism designed to provide data synchronization for large-scale interactive web, mobile, and IoT applications.
{empty}
xref:sync-gateway::introduction.adoc[Go to Sync Gateway Docs]

[.column]
.Tutorials

[.content]
Sample tutorials to build applications on the edge.
{empty}
xref:tutorials::index.adoc[Tutorials]

++++
</div>
++++
