// tag::basic[]
TIP: Positional parameters are set using the `-args` query parameter.

NOTE: Once a node has been successfully added, the Couchbase Server cluster indicates that a rebalance is required to complete the operation.

IMPORTANT: The node names passed to the `nodes` parameter must include the cluster administration port (by default 8091).
For example `WITH {"nodes": ["192.0.2.0:8091"]}` instead of `WITH {"nodes": ["192.0.2.0"]}`.

WARNING: Never stop or restart Couchbase Server before you first remove that node from a cluster.

CAUTION: Don't stick forks in power sockets.
// end::basic[]

// tag::complex[]
[IMPORTANT]
.Optional Title
====
Use an example block to create an admonition that contains complex content, such as:

* Lists
* Multiple paragraphs
* Source code
====
// end::complex[]

https://docs-staging.couchbase.com/server/5.1/n1ql/n1ql-language-reference/createindex.html
[caption=Attention]
IMPORTANT: We recommend that you do not create (or drop) secondary indexes when any node with a secondary index role is down as this may result in duplicate index names.

TIP: For better scalability and throughput, we recommend that you set the value of the `stale` parameter to `ok`.
With the stream-based views, data returned when `stale` is set to `ok` is closer to the key-value data, even though it might not include all of it.
