#!/bin/env groovy

pipeline {
  agent {
    dockerfile {
      dir 'docsearch'
      filename 'Dockerfile.jenkins'
    }
  }
  environment {
    CONFIG="${env.WORKSPACE}/docsearch/production-config.json"
    HOME='/docsearch'
    PIPENV_HIDE_EMOJIS=true
    PIPENV_NOSPIN=true
  }
  stages {
    stage('Install') {
      steps {
        sh '(cd /docsearch && pipenv install)'
      }
    }
    stage('Run') {
      steps {
        sh '(cd /docsearch && pipenv run python -m src.index)'
      }
    }
    stage('Activate') {
      steps {
        sh '(cd /docsearch && pipenv run python promote-index.py next_docs_couchbase prod_docs_couchbase)'
      }
    }
  }
}
