#!/bin/bash

CRED=~/.git-credentials
cp $CRED $CRED.backup # if it exists

set -euo pipefail
USER=$(gh api user -q .login)
TOKEN=$(gh auth token)
VALUE="https://${USER}:${TOKEN}@github.com"

echo "Updating $CRED:"
echo "   $VALUE"
echo "https://${USER}:${TOKEN}@github.com" > $CRED
