#!/bin/bash

CRED=~/.git-credentials

if [ -f $CRED ]; then
  BACKUP=$CRED.backup
  mv $CRED $BACKUP
  echo "Backed up credentials to $BACKUP"
fi

set -euo pipefail
USER=$(gh api user -q .login)
TOKEN=$(gh auth token)
VALUE="https://${USER}:${TOKEN}@github.com"

echo "Updating $CRED:"
echo "   $VALUE"
echo "https://${USER}:${TOKEN}@github.com" > $CRED
