= Add a New Documentation Page

To add a new page to the Couchbase documentation, you need to create a new AsciiDoc file. 

== Create a New AsciiDoc File

. Open the documentation repository that you want to work in with VS Code. 
+
TIP: If you enabled the *Open with Code* shortcut when you xref:install-git-and-editor[installed VS Code], you can right-click inside your file explorer window from a repository to quickly open it in VS Code.
. In the VS Code *Explorer* panel, navigate to the *pages* folder where you want to add a new page.
+
The folder structure for a documentation repository could look like the following: 
+
----
- <component-name>
    -- modules
        --- <module-name>
            ---- assets
            ---- examples
            ---- pages
            ---- partials
----
+
Specifically, the folder structure for this component, the `home` component of the Couchbase docs, looks like: 
+
----
- home
    -- modules
        --- contribute
            ---- assets
            ---- examples
            ---- pages
            ---- partials
        --- ROOT
            ---- assets
            ---- pages
            ---- partials
----
. Right-click the *pages* folder and click *New File*. 
. Enter a name for your new AsciiDoc file.
This filename will appear in the page's URL when it's published to our documentation site. 
+
Make sure your filename: 
+
** Uses lowercase letters (a-z). 
** Separates words with hyphens (`-`). 
** Does not use symbols or special characters, such as `!`, `@`, `#`, or others.
. End the filename with the AsciiDoc file extension, `.adoc`, and press kbd:[Enter].
+
VS Code automatically opens the new file. 
. On the first line of the new file, enter a xref:pages.adoc#doc-title[document title], starting with an `=`.
. Write your documentation using proper AsciiDoc syntax.
For more information about AsciiDoc syntax, see xref:basics.adoc[] or https://docs.asciidoctor.org/asciidoc/latest/[the AsciiDoc Language documentation^].
. Save the file, or take advantage of VS Code's autosave feature (menu:File[Auto Save]).

Any AsciiDoc file saved to a *pages* directory in an Antora documentation component is automatically published to the site.

== Next Steps

* xref:update-nav.adoc[Add a page to a component navigation menu].
* xref:build-site.adoc[Build the docs site locally to test and preview your changes].
