= Attributes and Roles
:page-toclevels: 3

Use attributes and roles to insert content or CSS styles into your pages. 

== Setting and Referencing Document Attributes

Use an AsciiDoc attribute to hold names, URLs, and reusable content phrases.

An attribute consists of a key-value pair set in a page header or in the playbook file for the documentation site. 
Some attributes are built-in to Asciidoctor. 
Others are defined especially for the Couchbase documentation or by the writer.

Adding an attribute to a document header makes an attribute available to an entire page and all of its includes.
Each attribute must be entered on a separate line, known as an attribute entry.
The syntax of an attribute entry as follows:

----
 :name: value
----

In this case, `name` is the name of the attribute and `value` is the optional value.
The following example shows a document header with multiple included attributes: 

.Examples of document attributes
[source,asciidoc]
....
= Page Title
:page-topic-type: concept <1>
:source-language: javascript <2>
:url-downloads: https://www.couchbase.com/downloads <3>
:tabs: <4>

Download Sync Gateway from the {url-downloads}[Couchbase downloads page]. <5>

[source] <6>
----
Snippet of javascript source code
----
....
<1> Attribute names that start with `page-` are specially handled by Antora.
<2> A value can be assigned to a built-in attribute in the document header.
<3> Writers can set and define their own attributes.
<4> Some attributes are assigned an implicit value.
In this case, the tabs feature is turned on by setting `tabs`.
<5> Reference an attribute in the body of the document by entering the attribute name inside a set of curly brackets (`+{attribute-name}+`).
<6> Code blocks are assigned the source language `javascript`.

== Required Document Attributes 

The following document attributes must be included for every AsciiDoc file stored in a *pages* directory: 

include::partial$available-attributes.adoc[tag=required]

== Optional Document Attributes

You can also use the following optional attributes: 

include::partial$available-attributes.adoc[tag=optional]

Antora also assigns several page attributes on each page to provide information about the component, version, and module where a page is located.
You can find a list of these attributes in the https://docs.antora.org/antora/latest/page/intrinsic-attributes/[Antora documentation^].

See the https://github.com/couchbase/docs-site/blob/master/antora-playbook.yml[production^] and https://github.com/couchbase/docs-site/blob/master/antora-playbook-staging.yml[staging^] Antora playbooks to review which AsciiDoc attributes are currently set and unset for all of the Couchbase documentation pages.

== Unsetting a Document Attribute

Some built-in attributes are set (turned on) by default and set for all of the Couchbase document in the playbook.

For example, the `sectids` attribute is turned on by default and automatically generates section IDs for all Couchbase documentation pages.
To unset (turn off) an attribute on a page, prefix the name with a bang (`!`):

[source,asciidoc]
----
= Page Title
:!sectids:
----

== Using Roles

A role applies alternative or additional CSS styles to a document, block, or phrase.
The styles for each role are defined by the code in the https://github.com/couchbase/docs-ui[docs-ui repository^].

=== Inline Roles 

Add a role to a block or phrase by prefixing the role name with a dot and inserting it between a set of square brackets:

[source,asciidoc]
----
[.role-name]`I'm a phrase with an assigned role!`
----

As stated in the https://docs.asciidoctor.org/asciidoc/latest/attributes/role/[AsciiDoc documentation^], inline elements must be surrounded by formatting syntax to be assigned a role. 

You can add multiple roles to a single block or phrase by separating each role name with a period (`.`):

[source,asciidoc]
----
[.role1 .role2]*I'm a phrase with an assigned role!*

[.role1 .role2]
\----
I'm a block with an assigned role!
\----
----

=== Inline Roles for Editions, Versions, and Deprecation

Couchbase Documentation created inline page roles for marking sections of documentation as deprecated, for a specific Couchbase Server version, or for marking sections as applying to a specific product edition - similar to <<page-edition,the :page-edition: attribute>>. 

You can use the following inline roles to mark sections of text in your documentation: 

|==== 
| Role | Example 

a|
[source,asciidoc]
----
[.edition]#{enterprise}#
----
a| [.edition]#{enterprise}# 

This text applies to Couchbase Server Enterprise Edition 

a| 
[source,asciidoc]
----
[.edition]#{community}#
----
a| [.edition]#{community}# 

This text applies to Couchbase Server Community Edition 

a| 
[source,asciidoc]
----
[.status]#Couchbase Server x.x.x#
----
a| [.status]#Couchbase Server 7.6.2#

This text applies to Couchbase Server version 7.6.2 

a| 
[source,asciidoc]
----
[.deprecated]#Deprecated#
----
a| [.deprecated]#Deprecated#

This text applies to a deprecated feature 

|====

=== Page Roles

Assigning a role to a page applies that role to the entire page, rather than a specific block or phrase.
`page-role` is an example of a <<Using Page Attributes,page attribute>>.
It must be defined in the document header.

Unlike with blocks and phrases, page roles are not prefixed with a dot and must be separated by a single space (following the same rules as CSS classes).

The Couchbase documentation currently supports two page roles:

* `tiles`
* `-toc`

These roles are often combined, as you can see in this example:

[source,asciidoc]
----
= Document Title
:page-role: tiles -toc

Page contents.
----

You can see the `tiles -toc` page role combination in action on the xref:server:getting-started:starter-kits.adoc[Starter Kits page].
The tiles role arranges the secondary section titles as tiles (in two columns).
The -toc role tells the UI template not to add a table of contents (TOC) to the page.

== Using Page Attributes

Certain document attribute names are reserved specifically for use with Antora.
These are know as page attributes.
All page attributes begin with the `page-` prefix.
The prefix is removed and the remainder is passed on to the UI as metadata.
For the most part, it's up to the UI to decide how to use this information.

Antora has several https://docs.antora.org/antora/latest/page/intrinsic-attributes/[built-in page attributes^], and some other attributes have been added to the Couchbase UI.

WARNING: Do not create your own attributes that conflict with the names of any built-in page attributes or page attributes that are already in use. 

=== Custom Page Attributes

Use custom page attributes to pass information from the document to the UI.
Use the https://github.com/couchbase/docs-ui[docs-ui repository^] to control what these attributes actually do with the contents of a page. 
