= Base and Working Branches

A base branch contains the original source documentation.
You create working branches from a base branch and send pull requests to a base branch for integration.
// define base branch
A working branch isolates changes that solve a single issue.
A pull request submitted from a working branch that only contains closely related changes is easier to test, review, and merge.

[#base-branch]
== Choose the Right Base Branch
//Are we going to forward port or back port?

The Couchbase documentation repositories maintain two types of base branches: master and release.

The master branch (`master`) contains documentation for unreleased features and the future product version.
New documentation for the next product version, its features, and non-bug related improvements should be based off of the master branch.

Release branches (`release/$.$`) contain the documentation specific to a corresponding stable product release.
Fixes related to product bugs and documentation errors in stable releases should be based off of the oldest supported release branch that is affected by the change.
For example, if a broken code snippet is discovered in the Server 5.5 and 5.1 documentation, the working branch to fix this issue would be created from the `release/5.1` base branch.

If you're unsure which branch to create your working branch from, check the associated issue's *Affects versions* field, or, in its comment section, ask the Docs team for more information.
Also note that a few of the repositories use custom branch names, see xref:repositories.adoc#repo-special[Repositories that Require Special Handling] for more information.

[#work-branch]
== Create a Working Branch

Always make a new working branch for your work, no matter how small the change.

. Open a terminal and change into the repository directory that contains the files you want to edit.

 $ cd path/to/repository-folder

. Download the latest changes from the upstream repository.

 $ git fetch upstream

. <<base-branch,Choose the right branch>> to base your changes on and check it out.

 $ git checkout name-of-base-branch

. Create a working branch from the base branch and checkout the working branch.
+
--
 $ git checkout -b DOC-$$$$

The name of a working branch should match it with the issue it resolves.
For example, if you're resolving DOC issue #3891, you'd name the working branch `DOC-3891`.
--

== Next Steps

* xref:edit-pages.adoc[Edit existing documentation].
* xref:add-pages.adoc[Add new documentation pages].
