= Build the Documentation Site Locally
:url-docs-antora: https://docs.antora.org/antora/1.1
:url-ssh: {url-docs-antora}/playbook/private-repository-auth/

. Open a terminal and switch into the _docs-site_ folder.

 $ cd path/to/docs-site

. Run Antora, using the `antora` command with the staging playbook:

 docs-site $ antora staging-antora-playbook

. The cloning progress of each component repository is displayed in the console, followed by any AsciiDoc or Antora warning and error messages.
The site generation is complete when the command prompt (`$`) reappears in the terminal.
. Antora generated the site into a directory named _public_.
Switch to it.

 docs-site $ cd public

. On some operating systems, you can open the site directly from the command line by typing `open` and the name of an HTML file.
+
--
 public $ open index.html

Or, you can navigate to and open _index.html_ using your file explorer or browser.
--

Now that you're set up to build the site locally, you can run Antora with a xref:test-site.adoc[local playbook] and test your documentation changes.

TIP: Antora relies on the SSH agent to authenticate private repositories on your behalf.
If Antora fails because it can't connect to the private repositories in the playbook, you're SSH agent probably isn't running.
See {url-ssh}[SSH Authentication^] to learn how to configure and run your SSH agent
