= Code Blocks for Example Code
:url-docs-antora: https://docs.antora.org/antora/latest/
:url-docs-adoc: https://asciidoctor.org/docs/user-manual
:url-examplesdir: {url-docs-antora}/modules/#examples-dir
:url-resource: {url-docs-antora}/page/resource-id/
:url-include-example: {url-docs-antora}/asciidoc/include-example/
:url-tags: {url-docs-adoc}/#by-tagged-regions
:url-indent: {url-docs-adoc}/#normalize-block-indentation

Use code blocks inside a documentation page to add example code. 

Code samples should be stored in the `examples` directory for a module and added to documentation pages with the <<include-code,`include::` directive>>.
Some SDK examples have been added to the special `devguide` module inside each SDK docs repository.
Using the `examples` directory and keeping code separate from AsciiDoc pages helps with our goal of automated code sample testing and maintenance. 

Do not insert example code without testing that your code works. 

== Code Example Formatting 

Add a source code example by adding a source block to an AsciiDoc page. 

Source blocks display content exactly as entered, preserving indents and line breaks. 

Add the attribute `[source,<language>]` to a source block to add code syntax highlighting in the published documentation.

For example, the following AsciiDoc: 

....
include::example$code-blocks.adoc[tag=dl-co]
....

Renders as: 

****
include::example$code-blocks.adoc[tag=dl]
****

If you need to add any commands to documentation that are run in the command line, use `[source,console]` and add a `$` to the start of each command. 

For example, the following AsciiDoc:

....
include::example$code-blocks.adoc[tag=console]
....

Renders as: 

****
include::example$code-blocks.adoc[tag=console]
****

TIP: Make sure to use `[source,console]` together with the `$` before each command.
`[source,console]` makes sure that the user does not copy the `$` character when they copy from a code block. 


[#callouts]
== Callout Numbers

WARNING: Do not use the built-in callout numbers to add annotations and explanations to your example code. 
For more information about alternatives, see xref:styleguide:examples.adoc#explaining-code-examples[Explaining Code Examples] in the style guide. 
The following section has been left for reference on the mechanics of code callouts, for when you encounter them in documentation. 

Callouts add annotations to lines in code blocks.
The first callout number must be placed after the final character on a code line.
The responding callout is listed below the block and followed by the annotation text.
Multiple callout numbers can be used on a single line.

[subs=-callouts]
....
include::example$code-blocks.adoc[tag=callouts]
....

Will render as: 

include::example$code-blocks.adoc[tag=callouts]

TIP: To make callouts copy-and-paste friendly, put them behind the line comment syntax of the code snippet's language.
For example, callouts in a YAML example are placed behind the hash symbol (`#`).

The callout list does not have to follow immediately after the code block containing the callouts.
For example, you can include an introductory sentence or paragraph between the code block and the callout list.

Instead of marking up each callout with its own number, such as `<1>`, `<2>`, `<3>`, you can use `<.>` for each callout.
When you use this method, the callouts are numbered automatically.

[#include-code]
== Inserting Examples with the Include Directive

Use the `include::` directive to insert a sample code file or tagged region from the `examples` directory into a file in the `pages` directory of a module. 
Using the `include::` directive also adds the btn:[View on GitHub] button to the code sample, so readers can view the source file directly. 

You need to know the resource ID of the example file to include it inside a page. 

For example, the following inserts the `contact.json` file into a file in the `pages` directory from the `examples` directory in the same module: 

....
.Query result
[source,json]
----
\include::example$contact.json[]
----
....

=== Insert Part of an Example 

If you only want to insert part of an example code file, add tags around the part of the sample you want to include, using the comment character from your source language - such as `//` or `#`.

Start a tagged region with `tag::<tag-name>`. 
End a tagged region with `end::<tag-name>`.

For example, the following Ruby code adds a `read-only` tag: 

....
# tag::read-only[]
options = Cluster::QueryOptions.new
options.readonly = true
cluster.query(
    'SELECT COUNT(*) AS airport_count FROM `travel-sample` WHERE type = "airport"',
    options)
# end::read-only[]
....

Then, in the square brackets (`[]`) at the end of the `include::` directive, add the tag name: 

....
.Read-only Query
[source,json]
----
\include::example$query.rb[tag=read-only]
----
....

////
== Try It Now

The Couchbase documentation integrates with https://couchbase.live to offer an interactive code console called "`Try It Now`".
This feature can be enabled per code block.

To add a "`Try It Now`" mode to a code block, you need two things:

. A standalone code sample that can be executing on couchbase.live
. The `try-it` role on the block to indicate that the code is compatible with couchbase.live

When the "`Try It Now`" mode is enabled, a btn:[Run Code] button will appear in the toolbar above the code block.
When the user clicks on this button, it will split the page into two panes, with the documentation on the left and the output console on the right.
It will also make the code block editable.
The reader can either reexecute the code using the refresh button above the output console or by clicking the btn:[Run Code] button again.
Clicking the btn:[Run Code] button submits the updated code, whereas the refresh button reexecutes the previous code.

Here's an example of a code block with the "`Try It Now`" mode enabled:

[source,asciidoc]
....
[source.try-it,js]
....
const couchbase = require('couchbase')

const cluster = new couchbase.Cluster('couchbase://127.0.0.1', {
  username: 'username', password: 'password'
})

const bucket = cluster.bucket('travel-sample')
const collection = bucket.defaultCollection()

const getDocument = async (key) => {
  try {
    const result = await collection.get(key)
    console.log(result)
  } catch (err) {
    console.error(err)
  }
}

getDocument('airline_10')
  .then(() => process.exit(0))
....
....

Here's how it appears when rendered:

[source.try-it,js]
....
const couchbase = require('couchbase')

const cluster = new couchbase.Cluster('couchbase://127.0.0.1', {
  username: 'username', password: 'password'
})

const bucket = cluster.bucket('travel-sample')
const collection = bucket.defaultCollection()

const getDocument = async (key) => {
  try {
    const result = await collection.get(key)
    console.log(result)
  } catch (err) {
    console.error(err)
  }
}

getDocument('airline_10').then(() => process.exit(0))
....

The code sample has to be compatible with couchbase.live.
The one exception is for Java.
You can use a public class with any class name and the supporting script will rewrite the class name as `Program`.
////

== Learn More

* xref:ids.adoc#code-block-id[Assign an ID to a code block].
* xref:tabs.adoc[Create a tabs set].
* xref:includes.adoc[Include examples].
* xref:includes.adoc#tag-region[Tag regions of an example file].

== Additional Resources

The Antora and Asciidoctor documentation provide more information about including code examples.

* {url-resource}[Antora resource ID structure^]
* {url-include-example}[Insert code snippets and files with the include directive^]
* {url-tags}[Select code regions with the tag macro^]
* {url-indent}[Normalize block indentation with the indent attribute^]
