= Code Blocks and Callouts
:url-docs-antora: https://docs.antora.org/antora/2.0
:url-docs-adoc: https://asciidoctor.org/docs/user-manual
:url-examplesdir: {url-docs-antora}/modules/#examples-dir
:url-resource: {url-docs-antora}/page/resource-id/
:url-include-example: {url-docs-antora}/asciidoc/include-example/
:url-tags: {url-docs-adoc}/#by-tagged-regions
:url-indent: {url-docs-adoc}/#normalize-block-indentation

== Code Blocks

Source code examples are entered into AsciiDoc listing blocks.
Listing block content is displayed exactly as entered, and any indents and endlines are preserved.
If the `source` style and a language are assigned to the block, the code is syntax highlighted on the site.

[listing]
.Delimited code block with title
....
include::example$code-blocks.adoc[tag=dl-co]
....
<1> Assign the block style `source` to the first position in the attribute list.
<2> Assign a source language to the second position.
<3> Code the contains blank lines must be entered into a delimited listing block (`----`).

Rendered as:

include::example$code-blocks.adoc[tag=dl]

Commands executed in a CLI are assigned the language `console` and lines are preceded by the command prompt (`$`).

....
include::example$code-blocks.adoc[tag=console]
....

Rendered as:

include::example$code-blocks.adoc[tag=console]

Short code snippets don't need delimiters as long as they don't contain blank lines or callouts.

....
include::example$code-blocks.adoc[tag=single]
....

Rendered as:

include::example$code-blocks.adoc[tag=single]

Code blocks can be grouped in a parent block element.

....
include::example$code-blocks.adoc[tag=group-code-blocks]
....

Rendered as:

include::example$code-blocks.adoc[tag=group-code-blocks]

[#callouts]
== Callout Numbers

Callouts add annotations to lines in code blocks.
The first callout number must be placed after the final character on a code line.
The responding callout is listed below the block and followed by the annotation text.
Multiple callout numbers can be used on a single line.

[source,subs=-callouts]
....
include::example$code-blocks.adoc[tag=callouts]
....

Rendered as:

include::example$code-blocks.adoc[tag=callouts]

TIP: To make callouts copy-and-paste friendly, put them behind the line comment syntax of the code snippet's language.
For example, callouts in a YAML example are placed behind the hash symbol (`#`).

[#include-code]
== Inserting Examples with the Include Directive

The include directive inserts an entire file or tagged region from a file stored in the _examples_ directory of a module into a code block.
Just specify the xref:includes.adoc[resource ID of the example file in the directive].

....
.Query result
[source,json]
----
\include::example$contact.json[]
----
....

== Learn More

* xref:ids.adoc#code-block-id[Assign an ID to a code block].
* xref:tabs.adoc[Create a tabs set].
* xref:includes.adoc[Include examples].
* xref:includes.adoc#tag-region[Tag regions of an example file].

== Additional Resources

The Antora and Asciidoctor documentation provide more information about including code examples.

* {url-resource}[Antora resource ID structure^]
* {url-include-example}[Insert code snippets and files with the include directive^]
* {url-tags}[Select code regions with the tag macro^]
* {url-indent}[Normalize block indentation with the indent attribute^]
