= Documentation Repository Organization
//Couchbase uses Antora to manage and build docs.couchbase.com.

The Couchbase documentation repositories use a standard directory structure and nomenclature so Antora can collect the content files and build docs.couchbase.com.

== Key Directories and Files

Component::
A documentation component contains AsciiDoc files, their optional assets and examples, one or more optional navigation files, and a component descriptor file per repository.
All of the files in a component are versioned together.
+
While it is common to find all of a component's files in a single repository, a component can be distributed across several repositories.
The Server component is aggregated from the _docs-server_, _couchbase-cli_, _backup_, and _asterix-opts_ repositories.
+
A component isn't recognized by a repository or directory name.
Instead, the presence of file named _antora.yml_ indicates that the directories files nested under it are part of a component.

Component Descriptor::
A component must contain a component descriptor file named _antora.yml_.
When Antora finds _antora.yml_ in a repository, it knows it has located a component (or part of component).
The component descriptor tags the files under its hierarchy with the specified component name and version.

Module::
A module is a discrete bundle of content, including text, images, and other source materials, organized in a hierarchy of folders by content format, then by optional topic if needed.
A module is stored in a component's _modules_ directory.
A component can contain one or more modules.

ROOT Module::
The ROOT module contains all the content that's directly associated with the component itself.
When pages in the ROOT module are published, these pages are promoted a level above any other modules' pages in that component's URL.

Pages::
The _pages_ directory contains a module's AsciiDoc files.
These files are automatically converted to standalone HTML pages.
See xref:pages.adoc[Standard Document Structure] to learn how to structure an AsciiDoc file.

Partials::
The _{blank}_partials_ directory contains AsciiDoc files that aren't standalone pages.
These files are referenced by an include directive from a document in the _pages_ directory.

Assets::
Multimedia and supplemental files, organized by format, are stored in the _assets_ directory.
Photographs, screenshots, and graphic files in _assets/images_ are inserted into pages using the xref:basics.adoc#images[AsciiDoc image macro].

Examples::
Non-AsciiDoc files, such as source code and data values, are stored in the _examples_ directory.
These files are often inserted into listing blocks using the xref:code-blocks.adoc[AsciiDoc include directive].

Navigation::
A navigation file, often named _nav.adoc_ contains one or more AsciiDoc lists.
Antora uses these files to build the site's component navigation menus.
A navigation file must be declared in the component descriptor in order to be displayed in the component's navigation menu.

== Next Step

xref:edit-pages.adoc[Edit existing documentation]
//. Add new pages, assets, examples, or partial files.
