= Site Extensions

Test and document your Asciidoctor.js or Antora extensions here.

== Inline JIRA macro

=== Usage

[source,asciidoc]
----
== Fixed issues:

* jira:JSCBC-1234[]: reversed the polarity of the neutron flow
* jira:AV-2345[]: frobnicated the gostaks
* jira:DOC-999[The dreaded DOC-999 ticket...]: implemented jira macro
----

[source,yml]
.antora-playbook.yml
----
asciidoc:
  attributes:
    # ...
    url-issues: https://issues.couchbase.com/browse
    url-issues-JSCBC: https://issues.couchbase.com/browse
    url-issues-AV: https://couchbasecloud.atlassian.net/browse
  extensions:
  # ...
  - ./lib/inline-jira-macro.js
----

=== Output

==== Fixed issues:

* jira:JSCBC-1234[]: reversed the polarity of the neutron flow
* jira:AV-2345[]: frobnicated the gostaks
* jira:DOC-999[The dreaded DOC-999 ticket...]: implemented jira macro

== Markdown Block

[source,asciidoc]
----
[markdown]
--
Filter some text with [Markdown](https://commonmark.org/help/) syntax.
--
----

Results in:

[markdown]
--
Filter some text with [Markdown](https://commonmark.org/help/) syntax.
--


[NOTE]
--
This is not implemented with a full Markdown parser.
See link:https://github.com/asciidoctor/kramdown-asciidoc/issues/7[issue]
with a link to the "naive series of regexes" used as starting point.

(And note that we use Open 
link:https://docs.asciidoctor.org/asciidoc/latest/blocks/delimited/#summary-of-structural-containers[structural context], 
with `--` delimiters, and headings don't work inside these.)

This feature is intended for handling OpenAPI specs, which can contain Markdown,
however openapi-generator has link:https://github.com/OpenAPITools/openapi-generator/issues/11396[poor Asciidoc handling],
so instead we add the block delimiters in the template, and let the block filter handle it.
--
