= Contributing to the Couchbase Documentation
// Settings
:hide-uri-scheme:
// URLs
:url-issues: https://issues.couchbase.com
:url-issues-doc: {url-issues}/projects/DOC/issues
:url-docs: https://docs.couchbase.com
:url-2056: {url-issues}/browse/DOC-2056

Thank you for taking the time and effort to improve the Couchbase documentation.

//The following is a short guide for contributing to the Couchbase documentation.

== Reporting Bugs and Requesting Enhancements

All bugs and enhancements for the Couchbase documentation are tracked on the {url-issues-doc}[DOC project issue board].
If you find an error or think there is room for improvement please don't keep it to yourself, even if you don't intend to make the change yourself!
Raise a DOC bug and someone on the team will look at it.

You can also raise a DOC issue by clicking the btn:[Feedback?] button in the bottom-right of any page on {url-docs}.

=== How do I submit a good DOC issue?

Use a clear and descriptive title::
E.g "`Instructions for disabling THP on RHEL/Centos 7 and later do not work`".

Describe the problem or enhancement in full::
For any problem, describe it in detail, including any expected results and how they differ from the real results.
Remember, the documentation team are not experts in every aspect of Couchbase.
For that reason, be as descriptive as possible, providing the correct text or command.
This drastically reduces the time it takes to resolve the issue.
{url-2056}[DOC-2056] is an example of a well-written DOC bug which allowed the assigned writer to make the necessary changes quickly.

== Contributing Changes

If you want to contribute the changes to resolve an issue yourself, then this is greatly encouraged!

You can submit simple changes, such as typo fixes and minor clarifications, using the <<simple>>.
For more extensive content additions and updates, or if you prefer to work locally, see the Docs Writer Complete Workflow.
// add workflow xref

[#simple]
== Simple Edits Workflow
//Quick Edits Workflow

For simple edits and fixes, you can edit the content directly on GitHub by clicking the edit icon found on many of the documentation pages.
// add inline image

Once you've made the changes, replace the default "`Update this-page.adoc`" commit message with a short, direct description of your change, and click btn:[Commit Changes].
Then follow the on-screen instructions to open a pull request.
