= Install Git and an AsciiDoc Editor
:url-atom-docs: https://flight-manual.atom.io/getting-started/sections/installing-atom
:url-linux: {url-atom-docs}/#platform-linux
:url-mac: {url-atom-docs}/#platform-mac
:url-windows: {url-atom-docs}/#platform-windows

== Create a GitHub Account

The Couchbase documentation is stored on GitHub, so if you don't have a GitHub account, you need to https://github.com/join[create one^].

== Download and Install Git

To clone and work with Git repositories on your device, i.e., local repositories, install Git using your operating system's package manager.
Alternatively, you can download it from the https://git-scm.com/downloads[Git project^].

== Install an AsciiDoc Editor

AsciiDoc is the markup language Couchbase uses for writing documentation.
You can write an AsciiDoc document using a plain text editor or integrated development environment (IDE).
If you don't have a preferred text editor or IDE, install Atom and the listed AsciiDoc packages for an enhanced experience.

[#install-atom]
=== Download and Install Atom

Atom is an open source, extensible text editor that works on Linux, macOS, and Windows.

. Go to the https://atom.io/[Atom home page^].
The Atom home page should detect your operating system automatically and provide the correct download options.
. Download and install Atom.
Use the links below for additional installation instructions.
** {url-linux}[Atom for Linux^]
** {url-mac}[Atom for macOS^]
** {url-windows}[Atom for Windows^]

[#adoc-packages]
=== Install the AsciiDoc Packages

. Start Atom and go to menu:Atom[Preferences] or press kbd:[Ctrl+,].
This opens the Settings panel.
. In the sidebar on the left, click btn:[Install].
. In the input field labeled *Search packages*, enter each package listed below, and install them.

language-asciidoc::
The `language-asciidoc` package provides AsciiDoc syntax highlighting and snippets.

asciidoc-preview::
The `asciidoc-preview` package renders a preview an AsciiDoc document in Atom.

== Next Step

xref:install-antora.adoc[Install Antora].
