= Install Antora
:url-docs-antora: https://docs.antora.org/antora/latest
:url-linux: {url-docs-antora}/install/linux-requirements/
:url-macos: {url-docs-antora}/install/macos-requirements/
:url-windows: {url-docs-antora}/install/windows-requirements/
:url-install: {url-docs-antora}/install/install-antora/

== Install System Prerequisites

Antora runs on most Linux distributions, macOS, and Windows.
If you've never used Antora, you may need to install a base build tools package and Node 8.
Follow the prerequisite instructions for your operating system:

* {url-linux}[Linux: Install base build tools and Node^]
* {url-macos}[macOS: Install Xcode and Node^]
* {url-windows}[Windows: Install Chocolaty and Node^]

== Install the Antora CLI and Site Generator

To generate the Couchbase documentation, you need the Antora command line interface (CLI) and the Antora site generator.

. Open a terminal and install the Antora CLI:

 $ npm i -g @antora/cli

. Verify the `antora` command is available on your PATH:
+
--
 $ antora -v

If installation was successful, you should see the Antora version number displayed in the console.
--
. Install the Antora site generator:

 $ npm i -g @antora/site-generator-default

== Next Step

xref:playbook.adoc[Get the Couchbase documentation site playbook].

////
You can also consult the {url-install}[installation instructions in the Antora documentation] for more details and troubleshooting tips.
Depending on the prerequisites you installed, follow the <<npm,using npm>> or <<yarn,using Yarn>> steps to install the CLI and site generator.

[#yarn]
=== Using Yarn

. Open a terminal and install the Antora CLI:

 $ yarn global add @antora/cli

. Verify the `antora` command is available on your PATH:

 $ antora -v

.. If installation was successful, you should see the Antora version number displayed in the console.

. Install the Antora site generator:

 $ yarn global add @antora/site-generator-default
////
