= Repository Requirements and Organization
:url-git-cb:  https://github.com/couchbase
:url-git-labs: https://github.com/couchbaselabs
:url-git-server: {url-git-cb}/docs-server
:url-git-cli: {url-git-cb}/couchbase-cli
:url-git-backup: {url-git-cb}/backup
:url-git-lite: {url-git-labs}/docs-couchbase-lite
:url-git-sync: {url-git-labs}/docs-sync-gateway
:url-git-sdk-c: {url-git-cb}/docs-sdk-c
:url-git-sdk-go: {url-git-cb}/docs-sdk-go
:url-git-sdk-java: {url-git-cb}/docs-sdk-java
:url-git-sdk-dotnet: {url-git-cb}/docs-sdk-dotnet
:url-git-sdk-nodejs: {url-git-cb}/docs-sdk-nodejs
:url-git-sdk-php: {url-git-cb}/docs-sdk-php
:url-git-sdk-python: {url-git-cb}/docs-sdk-python
:url-git-kafka: {url-git-cb}/kafka-connect-couchbase
:url-git-spark: {url-git-cb}/couchbase-spark-connector
:url-git-home: {url-git-cb}/docs-site
:url-git-operator: {url-git-cb}/couchbase-operator
:url-git-asterix: {url-git-labs}/asterix-opt
//Couchbase uses Antora to manage and build docs.couchbase.com.

The Couchbase documentation is stored in multiple repositories that are organized in a standard directory structure.

[#repo-urls]
== Distributed Repositories

The Couchbase documentation is distributed across several organizations and multiple repositories on GitHub.
The following repositories accept contributions via the regular workflow and use a standard branch pattern.

* {url-git-server}[Server^]
* {url-git-lite}[Lite^]
* {url-git-sync}[Sync Gateway^]
* {url-git-sdk-c}[C SDK^]
* {url-git-sdk-go}[Go SDK^]
* {url-git-sdk-java}[Java SDK^]
* {url-git-sdk-dotnet}[.NET SDK^]
* {url-git-sdk-nodejs}[Node.js SDK^]
* {url-git-sdk-php}[PHP SDK^]
* {url-git-sdk-python}[Python SDK^]
* {url-git-kafka}[Kafka Connector^]
* {url-git-spark}[Spark Connector^]
* {url-git-home}[Home and Contribute^]

[#repo-special]
=== Repositories that Require Special Handling

Some Couchbase repositories can only accept contributions via Gerrit, use custom branch patterns, and have additional content and AsciiDoc requirements.
You should review the project's README for the latest contributing requirements and contact the project lead before working on documentation stored in these repositories.

==== CLI and Backup

The CLI and Backup repositories use the Gerrit workflow and custom branch patterns.
Additionally, the AsciiDoc files in these repositories are used to create two sets of documentation: 1. the CLI and Backup pages incorporated in Couchbase Server on docs.couchbase.com, and 2. standalone man pages that are bundled with the Server software.
When editing these files, use the man page section structure and formatting.

* {url-git-cli}[CLI^]
* {url-git-backup}[Backup^]

//make note to special xref link text formatting

==== Autonomous Operator

The Autonomous Operator repository uses the Gerrit workflow and custom branch patterns.
The documentation is stored in _docs/user_.

* {url-git-operator}[Autonomous Operator^]

==== Analytics

The Analytics service documentation is maintained in collaboration with the AsterixDB project.
See its {url-git-asterix}/blob/master/README.md[README] for contributing instructions.

* {url-git-asterix}[Analytics^]

[#dir-structure]
== Directory Structure and Key Files

The Couchbase repositories that contain documentation use a standard directory structure and nomenclature.
This ensures that Antora can locate the documentation components, collect the content files, and then build docs.couchbase.com.

Component::
A documentation component contains AsciiDoc files, their optional assets and examples, one or more optional navigation files, and a component descriptor file per repository.
All of the files in a component are versioned together.
+
While it is common to find all of a component's files in a single repository, a component can be distributed across several repositories.
The Server component is aggregated from the _docs-server_, _couchbase-cli_, _backup_, and _asterix-opt_ repositories.
+
A component isn't recognized by a repository or directory name.
Instead, the presence of file named _antora.yml_ indicates that the directories and files nested under it are part of a component.

Component Descriptor::
A component must contain a component descriptor file named _antora.yml_.
When Antora finds _antora.yml_ in a repository, it knows it has located a component (or part of component).
The component descriptor tags the files under its hierarchy with the specified component name and version.

Module::
A module is a discrete bundle of content, including text, images, and other source materials, organized in a hierarchy of folders by content format, then by optional topic if needed.
A module is stored in a component's _modules_ directory.
A component can contain one or more modules.

ROOT Module::
The ROOT module contains all the content that's directly associated with the component itself.
When pages in the ROOT module are published, these pages are promoted a level above any other modules' pages in that component's URL.

Pages::
The _pages_ directory contains a module's AsciiDoc files.
These files are automatically converted to standalone HTML pages.
See the xref:pages.adoc[Standard Document Structure] to learn how to structure an AsciiDoc file.

Partials::
The _{blank}_partials_ directory contains AsciiDoc files that aren't standalone pages.
These files are referenced by an include directive from a document in the _pages_ directory.

Assets::
Multimedia and supplemental files, organized by format, are stored in the _assets_ directory.
Photographs, screenshots, and graphic files in _assets/images_ are inserted into pages using the xref:basics.adoc#images[AsciiDoc image macro].

Examples::
Non-AsciiDoc files, such as source code and data values, are stored in the _examples_ directory.
These files are often inserted into listing blocks using the xref:code-blocks.adoc[AsciiDoc include directive].

Navigation::
A navigation file, often named _nav.adoc_ contains one or more AsciiDoc lists.
Antora uses these files to build the site's component navigation menus.
A navigation file must be declared in the component descriptor in order to be displayed in the component's navigation menu.

== Next Steps

. xref:branches.adoc#base-branch[Choose a base branch].
. xref:branches.adoc#work-branch[Create a working branch].
