= About Couchbase Documentation Repositories
:url-git-cb: https://github.com/couchbase
:url-git-labs: https://github.com/couchbaselabs
:url-git-server: {url-git-cb}/docs-server
:url-git-cli: {url-git-cb}/couchbase-cli
:url-git-backup: {url-git-cb}/backup
:url-git-lite: {url-git-labs}/docs-couchbase-lite
:url-git-sync: {url-git-labs}/docs-sync-gateway
:url-git-sdk-c: {url-git-cb}/docs-sdk-c
:url-git-sdk-cxx: {url-git-cb}/docs-sdk-cxx
:url-git-sdk-dotnet: {url-git-cb}/docs-sdk-dotnet
:url-git-sdk-go: {url-git-cb}/docs-sdk-go
:url-git-sdk-java: {url-git-cb}/docs-sdk-java
:url-git-sdk-kotlin: {url-git-cb}/docs-sdk-kotlin
:url-git-sdk-nodejs: {url-git-cb}/docs-sdk-nodejs
:url-git-sdk-php: {url-git-cb}/docs-sdk-php
:url-git-sdk-python: {url-git-cb}/docs-sdk-python
:url-git-sdk-ruby: {url-git-cb}/docs-sdk-ruby
:url-git-sdk-scala: {url-git-cb}/docs-sdk-scala
:url-git-sdk-common: {url-git-cb}/docs-sdk-common
:url-git-home: {url-git-cb}/docs-site
:url-git-operator: {url-git-cb}/couchbase-operator
:url-git-cmos: {url-git-labs}/observability
:url-git-asterix: {url-git-cb}/asterixdb
:url-git-analytics: {url-git-cb}/cbas-core
:url-git-elastic: {url-git-labs}/couchbase-elasticsearch-connector
:url-git-devex: {url-git-labs}/docs-devex
:url-git-swagger: {url-git-labs}/cb-swagger
:url-git-kafka: {url-git-cb}/kafka-connect-couchbase
:url-git-spark: {url-git-cb}/couchbase-spark-connector

The Couchbase Documentation site is built using multiple GitHub repositories. 
Each product tends to have its own GitHub repository or repositories.
Some repositories contain common files for multiple products.

For a quick overview on some terminology and concepts related to GitHub repositories in general, see https://docs.github.com/en/repositories/creating-and-managing-repositories/about-repositories[About repositories in the GitHub Documentation^].

Each repository follows the standard structure for an Antora component and its modules.
For more information about our specific Antora repository file structure, see <<dir-structure,>>.

[#repo-urls]
== Documentation Repository Roster

The Couchbase documentation is stored several organizations and multiple repositories on GitHub.
The following repositories accept contributions via the regular workflow and use a standard branch pattern.

* {url-git-server}[Couchbase Server^]
* {url-git-devex}[Developer Docs^]
* {url-git-swagger}[REST APIs^]
* {url-git-lite}[Couchbase Lite^]
* {url-git-sync}[Sync Gateway^]
* {url-git-sdk-c}[C SDK^]
// * {url-git-sdk-cxx}[{cpp} SDK^]
* {url-git-sdk-dotnet}[.NET SDK^]
* {url-git-sdk-go}[Go SDK^]
* {url-git-sdk-java}[Java SDK^]
* {url-git-sdk-kotlin}[Kotlin SDK^]
* {url-git-sdk-nodejs}[Node.js SDK^]
* {url-git-sdk-php}[PHP SDK^]
* {url-git-sdk-python}[Python SDK^]
* {url-git-sdk-ruby}[Ruby SDK^]
* {url-git-sdk-scala}[Scala SDK^]
* {url-git-sdk-common}[SDK Common^]
* {url-git-home}[Home and Contribute^]

For a complete list, see the Documentation Repos Master List on the internal Couchbase Confluence. 

[#repo-special]
=== Repositories that Require Special Handling

Some Couchbase repositories only accept contributions via Gerrit, use custom branch patterns, and have additional content and AsciiDoc requirements.
Review the project's README for the latest contributing requirements, or ask another Couchbase Documentation team member.

==== CLI

The CLI repository uses the Gerrit workflow and custom branch patterns.
Additionally, the AsciiDoc files in this repository are used to create two sets of documentation:

1. The CLI pages incorporated in the Couchbase Server component.
2. Standalone man pages that are bundled with the Server software.

When editing these files, use the man page section structure and formatting.
//make note to special xref link text formatting

* {url-git-cli}[CLI^]

==== Connectors

The connector repositories use the Gerrit workflow.

* {url-git-elastic}[Elasticsearch Connector^]
* {url-git-kafka}[Kafka Connector^]
* {url-git-spark}[Spark Connector^]

[#repo-private]
=== Private Repositories

Some Couchbase repositories are private.
Only Couchbase employees can contribute to the documentation in these components.

==== Backup

The Backup repository uses the Gerrit workflow and custom branch patterns.
Like the CLI repository, this repository is used to create the Backup pages in the Couchbase documentation, and standalone man pages.

==== Autonomous Operator

The Autonomous Operator repository uses the Gerrit workflow and custom branch patterns.

==== Analytics

The Analytics service documentation uses the Gerrit workflow.
It is maintained in collaboration with the {url-git-asterix}[AsterixDB] project.

[#dir-structure]
== Directory Structure and Key Files

include::partial$component-terms.adoc[]

== Next Steps

. xref:create-branches.adoc#base-branch[Choose a base branch].
. xref:create-branches.adoc[Create a working branch for your changes].
