= Send Your Changes for Review

After you complete your changes and fixed any warnings and errors reported by Antora, it's time to commit and push your working branch to your remote repository.

[#commit]
== Commit, Rebase, and Push

. Add the new and changed files.

 $ git add file-path-and-name

. Commit your changes.

 $ git commit -m "fix magic bucket example"

. Fetch any upstream base branch changes.

 $ git fetch upstream name-of-base-branch

. If the upstream base branch has changed, rebase your working branch against it.

 $ git rebase upstream/name-of-base-branch

. Push your working branch to your remote fork on GitHub.

 $ git push origin DOC-$$$$

== Send Changes for Review

To send your changes for review you can:

* <<pr, Submit a GitHub pull request>>, or
* <<submit-a-gerrit-change-request,Submit a Gerrit change request>>

[#pr]
=== Submit a GitHub Pull Request

After you push your working branch to your remote repository on GitHub, you can submit a pull request to the upstream repository for review.

. Go to your repository on GitHub, and click btn:[Compare & pull request].
. On the Open a Pull Request screen, update the PR title if it needs clarification, and then click btn:[Create Pull Request].

=== Submit a Gerrit Change Request

Some projects use the Gerrit code review process.
The following sections describe the steps to initialize a repository with Gerrit and how to submit a change request.

==== Initial Account Setup

To submit your first documentation contribution you must sign the contributor license agreement.

. Open http://review.couchbase.org/[review.couchbase.org^].
. Log in using your GitHub credentials.
. http://review.couchbase.org/#/settings/agreements[Fill out the agreement] under _Settings > Agreements_.
. Configure SSH access.
.. Add your SSH key under _Settings > SSH Public Keys_.
+
NOTE: Do not forget to setup your username on the Settings screen.
.. Add an entry for http://review.couchbase.org/[review.couchbase.org] to your *.ssh/config* file.
+
[source,text]
----
Host review.couchbase.org
  HostName review.couchbase.org
  Port 29418
  User <Your gerrit Username>
----

==== Initial Project Setup

If a Couchbase project is using Gerrit for code reviews, you'll need to configure your local clone to submit changes on Gerrit.

. Download link:{attachmentsdir}/commit-msg.sh[commit-msg.sh].
. Save the *commit-msg.sh* script to *.git/hooks/commit-msg.sh* in the clone of the repository you are working on.
. Make that file executable.
+
[source,console]
----
chmod +x .git/hooks/commit-msg.sh
----
. You can test that you've setup the *commit-msg.sh* script correctly by doing a commit and then looking at the output of the `git log` command.
You should see a "Change-Id: I[hex]" line in your commit message text.
. Set up Gerrit as a new Git remote with the following command.
Replace *PROJECT_NAME* with the repository name.
+
[source,console]
----
git remote add gerrit ssh://review.couchbase.org:29418/[PROJECT_NAME].git
----
. Retrieve the latest changes from the Gerrit server.
+
[source,console]
----
git fetch gerrit
----

==== Code Workflow

Run through the following steps to submit a change on the Gerrit server.

. Create a new branch where *BRANCH_NAME* is the remote branch to commit changes to.
+
[source,console]
----
git branch bug_666 gerrit/[BRANCH_NAME]
----
. Checkout on the topic branch.
+
[source,console]
----
git checkout bug_666
----
. Push the changes to the Gerrit server.
+
[source,console]
----
git push gerrit HEAD:refs/for/[BRANCH_NAME]
----
If successful, you'll see a URL in the command output.
. Open that URL to access the Gerrit web page and add reviewers.
Adding a reviewer causes the change to show up in the reviewer's "Reviewable by me" list, and they also get notified by email.

== Next Step

Get an overview of the Docs team review process. (Pending)

////
== Submit a Pull Request

Once your changes are in a branch on GitHub it is time to submit them to the main couchbase repository.

This is done using pull requests, you can read more about pull requests in general at https://help.github.com/articles/creating-a-pull-request/.

== Pull Request Testing and Review

This section will focus on what happens once you have created your pull request from your fork's branch onto the master branch.

1. As soon as your pull request has been submitted, the continuous integration will trigger, this can be seen as the check 'PR-Build'.
This builds the entire documentation set including your changes to ensure that it builds successfully (thus preventing malformed dita from breaking master).
Once it has done this it will report back whether or not it was successful, along with a link to a preview of any pages which have been updated in the PR.
You can use these links to see what your changes will look like (and whether or not you think you need further changes).
Every time the content of the PR is updated, this will retrigger.

2. A member of the documentation team will review your pull request and let you know if any changes are required.
Usually you will be asked to make any necessary changes yourself.
Don't worry if you're asked to make changes, this is normal!

3. Once the reviewer is happy with the changes, they will backport them to any necessary branches (please let them know if you think it needs backporting to certain releases) and merge your changes.

== Publishing

Accepted changes are pushed to docs.couchbase.com twice a week, so you may need to wait a few days to see your changes go live.
////
