= Send Your Changes for Review

After you complete your changes and fixed any warnings and errors reported by Antora, it's time to commit and push your working branch to your remote repository.

[#commit]
== Commit, Rebase, and Push

. Add the new and changed files.

 $ git add file-path-and-name

. Commit your changes.

 $ git commit -m "fix magic bucket example"

. Fetch any upstream base branch changes.

 $ git fetch upstream name-of-base-branch

. If the upstream base branch has changed, rebase your working branch against it.

 $ git rebase upstream/name-of-base-branch

. Push your working branch to your remote fork on GitHub.

 $ git push origin DOC-$$$$

[#pr]
== Submit a Pull Request

After you push your working branch to your remote repository on GitHub, you can submit a pull request to the upstream repository for review.

. Go to your repository on GitHub, and click btn:[Compare & pull request].
. On the Open a Pull Request screen, update the PR title if it needs clarification, and then click btn:[Create Pull Request].

== Next Step

Get an overview of the Docs team review process. (Pending)

////
== Common Workflow

A common workflow can be found below:

```
# Only required when first setting up the local repo
git clone https://github.com/<your-user>/docs-cb4.git

cd docs-cb4

BRANCH=DOC-XXXX
# Ensure that we base our changes on master
git checkout master
# Creates a new branch with the desired name
git branch $BRANCH

# Creates the branch on your remote repo
git push origin $BRANCH

# Checks out the newly created branch
git checkout $BRANCH

# Edit the files in question

# Add the edited files to be committed
git add my_files

# Commit the edited files
git commit -m "DOC-XXXX: Created git workflow example"

# Push the updated changes to your remote repository
git push origin $BRANCH
```

== Submit a Pull Request

Once your changes are in a branch on GitHub it is time to submit them to the main couchbase repository.

This is done using pull requests, you can read more about pull requests in general at https://help.github.com/articles/creating-a-pull-request/.

== Pull Request Testing and Review

This section will focus on what happens once you have created your pull request from your fork's branch onto the master branch.

1. As soon as your pull request has been submitted, the continuous integration will trigger, this can be seen as the check 'PR-Build'.
This builds the entire documentation set including your changes to ensure that it builds successfully (thus preventing malformed dita from breaking master).
Once it has done this it will report back whether or not it was successful, along with a link to a preview of any pages which have been updated in the PR.
You can use these links to see what your changes will look like (and whether or not you think you need further changes).
Every time the content of the PR is updated, this will retrigger.

2. A member of the documentation team will review your pull request and let you know if any changes are required.
Usually you will be asked to make any necessary changes yourself.
Don't worry if you're asked to make changes, this is normal!

3. Once the reviewer is happy with the changes, they will backport them to any necessary branches (please let them know if you think it needs backporting to certain releases) and merge your changes.

== Publishing

Accepted changes are pushed to docs.couchbase.com twice a week, so you may need to wait a few days to see your changes go live.

Docs Git Workflow
Complete Docs Workflow
Local Edits Workflow
Regular/Standard Edits Workflow

* Branches
** Protected
** Working
* Commit
* Pull request
* Validation
* Review
* Publishing
////
