= Set Up Your Local Repository

You only need to do these steps the first time you contribute to a repository.

== Fork the Repository

Before you can contribute changes to the Couchbase documentation, you must fork the appropriate repository to your personal GitHub account.
The Docs CI runner automatically fails and closes any pull request (PR) that isn't submitted from a fork.

. Go to the appropriate repository on GitHub and click btn:[Fork].
See xref:repositories.adoc#repo-urls[Repository Organization] for the list of active repositories

.How to quickly find the right repository
****
To quickly find a page's source file, click on the image:edit.svg[,18,alt="edit"] icon at the top of the page.
You'll be taken to the page's repository.
Click btn:[Fork].

//Not all of the Couchbase documentation repositories can accept contributor pull requests at this time.
If there isn't an image:edit.svg[,18,alt="edit"] icon on the page, then the repository can't accept changes using the regular workflow.
See xref:repositories.adoc#repo-special[Repositories that Require Special Handling] for more information or propose fixes and improvements using the btn:[Feedback?] button at the bottom of the page.
****

== Clone the Repository

After you fork the repository, clone it to your device.

. Create or select the folder where you want to store the repository on your device.
. Open a terminal and change into the selected folder.

 $ cd path/to/folder

. Go to your repository on GitHub, and click btn:[Clone or download].
. Click the Clipboard icon to copy the repository's Git URL.
. In your terminal type `git clone`, paste the copied URL, and press kbd:[Enter].
For example, to clone your fork of the docs-server repository, you'd enter:

 $ git clone git@github.com:this-is-you/docs-server.git

. Change into the repository folder created by the clone operation.

 $ cd docs-server

== Sync with the Upstream Repository

You need to connect your local repository to the upstream repository so the two repositories can stay in sync.

. Go to the upstream repository on GitHub, and click btn:[Clone or download].
. Click the Clipboard icon to copy the repository's Git URL.
. In your terminal type `git remote add upstream`, paste the copied URL, and press kbd:[Enter].
For example, to connect to the remote upstream docs-server repository, you'd enter:

 $ git remote add upstream git@github.com:couchbase/docs-server.git

. View the configured upstream and origin values and confirm the URLs are correct.
+
--
 $ git remote -v

The origin URLs should point to your personal fork, and the upstream URLs should point to the repository in the Couchbase organization.
--

. Download upstream changes.

 $ git fetch upstream

Now you're ready to start working on the documentation.

== Next Steps

. xref:workflow-overview.adoc[Get an overview of the entire contributing workflow].
. xref:create-branches.adoc#base-branch[Choose a base branch].
. xref:create-branches.adoc#work-branch-atom[Create a working branch in Atom] or xref:create-branches.adoc#work-branch-cli[from the command line].
