= Set Up Your Local Git Workspace
:url-git-cb:  https://github.com/couchbase
:url-git-labs: https://github.com/couchbaselabs
:url-git-server: {url-git-cb}/docs-server
:url-git-cli: {url-git-cb}/couchbase-cli/tree/master/docs
:url-git-lite: {url-git-labs}/couchbase-lite-docs
:url-git-sync: {url-git-labs}/sync-gateway-docs
:url-git-sdk-c: {url-git-cb}/docs-sdk-c
:url-git-sdk-go: {url-git-cb}/docs-sdk-go
:url-git-sdk-java: {url-git-cb}/docs-sdk-java
:url-git-sdk-dotnet: {url-git-cb}/docs-sdk-dotnet
:url-git-sdk-nodejs: {url-git-cb}/docs-sdk-nodejs
:url-git-sdk-php: {url-git-cb}/docs-sdk-php
:url-git-sdk-python: {url-git-cb}/docs-sdk-python
:url-git-kafka: {url-git-cb}/kafka-connect-couchbase/tree/master/docs
:url-git-spark: {url-git-cb}/couchbase-spark-connector/tree/master/docs
:url-git-home: {url-git-cb}/docs-site/tree/master/home

You only need to do these steps the first time you're contributing to a repository.

* [x] Fork the appropriate repository into your GitHub account.
* [x] Create a clone of the repository on your device.
* [x] Connect your local repository with the upstream repository.

== Fork the Repository

WARNING: To contribute documentation changes, you must fork the appropriate repository to your personal GitHub account.
The Docs CI runner automatically fails and closes any pull request (PR) that isn't submitted from a fork.

The Couchbase documentation is stored in multiple repositories.

* {url-git-server}[Server]
* {url-git-cli}[CLI]
* {url-git-lite}[Lite]
* {url-git-sync}[Sync Gateway]
* {url-git-sdk-c}[C SDK]
* {url-git-sdk-go}[Go SDK]
* {url-git-sdk-java}[Java SDK]
* {url-git-sdk-dotnet}[.NET SDK]
* {url-git-sdk-nodejs}[Node.js SDK]
* {url-git-sdk-php}[PHP SDK]
* {url-git-sdk-python}[Python SDK]
* {url-git-kafka}[Kafka Connector]
* {url-git-spark}[Spark Connector]
* {url-git-home}[Docs Site (Docs Home and Contributing Guide)]

Go to the appropriate repository on GitHub and click btn:[Fork].

.When you can't find the right repository
****
Not all of the Couchbase documentation repositories can accept contributor pull requests at this time.
To quickly find the source file for the page you want to edit, click on the image:edit.svg[,18,alt="edit"] icon at the top of the page.
You'll be taken to the page's repository.
Click btn:[Fork].

If there isn't an image:edit.svg[,18,alt="edit"] icon on the page, then you can't submit changes to the file using a PR.
However, you can contribute proposed fixes and improvements using the btn:[Feedback?] button at the bottom of the page.
****

== Clone the Repository

After you fork the repository, clone the repository to your device.

. Create or select the folder where you want to store the repository on your device.
. Open a terminal and change into the selected folder.

 $ cd path/to/folder

. Go to your repository on GitHub, and click btn:[Clone or download].
. Click the Clipboard icon to copy the repository's Git URL.
. In your terminal type `git clone`, paste the copied URL, and press kbd:[Enter].
For example, to clone your fork of the docs-server repository, you'd enter:

 $ git clone git@github.com:this-is-you/docs-server.git

. Change into the repository folder created by the clone operation.

 $ cd docs-server

== Sync with the Upstream Repository

You need to connect your local workspace to the upstream repository so the two repositories can stay in sync.

. Go to the upstream repository on GitHub, and click btn:[Clone or download].
. Click the Clipboard icon to copy the repository's Git URL.
. In your terminal type `git remote add upstream`, paste the copied URL, and press kbd:[Enter].
For example, to connect to the remote upstream docs-server repository, you'd enter:

 $ git remote add upstream git@github.com:couchbase/docs-server.git

Now you're ready to start working on the documentation.

== Next Steps

. xref:workflow.adoc#work-branch[Create a working branch]
. xref:workflow.adoc#commit[Commit your changes]
. xref:workflow.adoc#pr[Submit a pull request]
