= Set Up Documentation Repositories

To contribute to the Couchbase Documentation, you need to get the repository that contains the documentation files onto your computer. 
For a quick overview on some terminology and concepts related to GitHub repositories, see https://docs.github.com/en/repositories/creating-and-managing-repositories/about-repositories[About repositories in the GitHub Documentation^].

You only need to do these steps the first time you contribute to a repository.

== Find the Correct Repository 

To start, you need to know which Couchbase Documentation repository contains the files you need to edit. 

TIP: You can quickly find the correct repository for a page by using the image:edit.svg[,16,role=icon] *Edit on GitHub* button at the top of a page on the Couchbase Docs site. 

Couchbase Documentation repositories are usually prefixed with `docs-`.

[#clone]
== Clone the Repository

NOTE: Contributors from outside Couchbase need to https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/fork-a-repo[fork documentation repositories^] to contribute changes.
If you're a Couchbase employee, DO NOT fork repositories to contribute to Couchbase Documentation.

After you have found the repository that you want to work in, you need to clone it onto your computer:

. On the GitHub page for the repository, click btn:[Code].
. In the *Local* tab, do one of the following: 
.. To copy a command to use in your terminal, click btn:[HTTPS] and then the btn:[Copy] icon.
Continue to <<clone-with-the-command-line,>>
.. To clone the repository using xref:install-git-and-editor.adoc#install-github-desktop[GitHub Desktop], click btn:[Open with GitHub Desktop].
Continue to <<clone-with-github-desktop,>>.
.. To clone the repository using VS Code, see <<clone-with-vs-code,>>.

=== Clone with the Command Line

To continue cloning the repository with the command line: 

. Do one of the following: 
.. Create a new folder on your computer where you want to store the files for the new repository.
Consider giving the folder the same name as the repository. 
.. Select an existing folder where you want to store the files for the new repository. 
. Open a new terminal window. 
. In your terminal, enter the following command, replacing `<path/to/folder>` with the path to your folder from Step 1, and press kbd:[Enter]: 
+
----
$ cd <path/to/folder>
----
. Type `git clone`, paste the URL you copied from GitHub, and press kbd:[Enter].
The command should look similar to the following: 
+
----
git clone https://github.com/couchbaselabs/docs-devex.git
----

Wait for the clone process to finish downloading the main branch of the repository onto your computer. 

=== Clone with GitHub Desktop 

To continue cloning the repository with GitHub Desktop, follow the instructions in the https://docs.github.com/en/desktop/adding-and-cloning-repositories/cloning-a-repository-from-github-to-github-desktop[GitHub Desktop documentation^].

Wait for the clone process to finish downloading the main branch of the repository onto your computer. 

=== Clone with VS Code 

To clone a repository using VS Code, follow the instructions in the https://code.visualstudio.com/docs/sourcecontrol/intro-to-git#_open-a-git-repository[VS Code documentation^].

== Next Steps

. xref:workflow-overview.adoc[Get an overview of the entire contributing workflow].
. xref:create-branches.adoc#base-branch[Choose a base branch].
. xref:create-branches.adoc#work-branch-vs-code[Create a working branch in VS Code] or xref:create-branches.adoc#work-branch-cli[from the command line].
