= Test Your Changes Locally

If you've never built the site on your device, complete the xref:install-antora.adoc[Install Antora] and xref:playbook.adoc[Get the Site Playbook Project] steps first.

== Generating the Site

. Open a terminal and switch (`cd`) to the _docs-site_ folder.
. Run Antora with your local playbook:

 docs-site $ antora local-antora-playbook

. The cloning progress of each component repository is displayed in the console, followed by any AsciiDoc or Antora warning and error messages.
.. A warning indicates that a document contains invalid AsciiDoc syntax.
Antora will continue to build the site, but pages generated from invalid AsciiDoc will not display correctly.
.. Errors cause the site build to fail.
. If no errors terminate the build, site generation is complete when the command prompt (`$`) reappears in the terminal.
. Antora generated the site into a directory named _public_.
Switch to it.

 docs-site $ cd public

. On some operating systems, you can open the site directly from the command line by typing `open` and the name of an HTML file.
+
--
 public $ open index.html

Or, you can navigate to and open _index.html_ using your file explorer or browser.
--

. Review your changes on the local site.
. Make additional edits if needed, and fix any documents that report warnings.
. Run Antora again and review your changes in the site.

When you're satisfied with your work and fixed any reported errors, it's time to send your changes upstream for review.

IMPORTANT: Since some of the respositories listed in the playbook are private, Antora will look for git credentials to use to connect to those repositories.
If Antora fails because it can't connect to the private repositories, you're git credentials likely aren't configured.
See xref:build-site.adoc#configure-git-credentials[git credentials] to learn how to configure the git credentials for Antora to use.

== Next Step

xref:send-pr.adoc#commit[Commit your changes and push them to your remote repository].
