= Workflow Overview

Use the following as a quick reference for the general workflow for contributing to Couchbase Documentation. 

NOTE: Contributors from outside Couchbase need to https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/fork-a-repo[fork documentation repositories^] to contribute changes.
If you're a Couchbase employee, DO NOT fork repositories to contribute to Couchbase Documentation.

To set up to contribute to Couchbase Documentation, you must: 

* [x] Clone a repository onto your computer.

To make a contribution or change to Couchbase Documentation, you must: 

* [x] xref:repositories.adoc[Review each repository's requirements].
* [x] xref:create-branches.adoc#base-branch[Choose a base branch].
* [x] xref:create-branches.adoc[Create a working branch for your changes].
* [x] xref:edit-pages.adoc[Fix existing documentation] or xref:add-pages.adoc[create a new documentation page].
* [x] xref:test-site.adoc[Build the site locally and test your changes].
* [x] xref:send-pr.adoc#commit[Commit and push your changes].
* [x] xref:send-pr.adoc#pr[Submit a pull request].
* [x] Make requested changes to your pull request.
* [x] Merge your pull request.
* [x] Delete your working branch. 

IMPORTANT: Always try to delete old, unmerged branches or branches that you have merged with a pull request (PR) when you're done with them.
This keeps our repositories tidy. 