= Docs Writer Workflow

WARNING: This page is not current.
Updates to reflect the new component-version architecture, repository and branch permissions, reserved names, reporting, and CI/CD process (triggers, hooks, integration testing) are in progress.
Initial release date: Aug 7.

== Submit a Pull Request

Once your changes are in a branch on GitHub it is time to submit them to the main couchbase repository.

This is done using pull requests, you can read more about pull requests in general at https://help.github.com/articles/creating-a-pull-request/.

== Pull Request Testing and Review

This section will focus on what happens once you have created your pull request from your fork's branch onto the master branch.

1. As soon as your pull request has been submitted, the continuous integration will trigger, this can be seen as the check 'PR-Build'.
This builds the entire documentation set including your changes to ensure that it builds successfully (thus preventing malformed dita from breaking master).
Once it has done this it will report back whether or not it was successful, along with a link to a preview of any pages which have been updated in the PR.
You can use these links to see what your changes will look like (and whether or not you think you need further changes).
Every time the content of the PR is updated, this will retrigger.

2. A member of the documentation team will review your pull request and let you know if any changes are required.
Usually you will be asked to make any necessary changes yourself.
Don't worry if you're asked to make changes, this is normal!

3. Once the reviewer is happy with the changes, they will backport them to any necessary branches (please let them know if you think it needs backporting to certain releases) and merge your changes.

== Publishing

Accepted changes are pushed to docs.couchbase.com twice a week, so you may need to wait a few days to see your changes go live.

////
Docs Git Workflow
Complete Docs Workflow
Local Edits Workflow
Regular/Standard Edits Workflow

* Branches
** Protected
** Working
* Commit
* Pull request
* Validation
* Review
* Publishing
////
