name: "on-push-yml"
run-name: ${{ github.actor }} is learning Github Actions
on: 
    push:
        branches:
            - docs-team
        paths:
            - '*.yml'
jobs:
    which-file-changed:
        runs-on: ubuntu-latest
        outputs:
            all_changed_files: ${{ steps.changed-files.outputs.all_changed_files }}
        steps:
            - uses: actions/checkout@v4

            - name: Get changed files
              id: changed-files
              uses: tj-actions/changed-files@v44
              with:
                matrix: true
                files: |
                    *.yml

    deploy:
        needs: which-file-changed
        strategy:
            matrix:
                playbook: ${{ fromJSON(needs.which-file-changed.outputs.all_changed_files) }}
        runs-on: ubuntu-latest
        uses: couchbase/docs-infra/.github/workflows/generic-antora-build.yml@master
        with:
            website-title: Couchbase Docs PREVIEW TEST
            website-url: https://preview.docs-test.couchbase.com
            environment: preview
            branch: docs-team
            playbook: ${{ matrix.playbook }}
            subdirectory: ${{ matrix.playbook }}
        secrets: inherit
    
#                 echo 
