name: Review Requested

on:
  pull_request:
    paths:
      - home/

jobs:
  vale:
    if: github.event.requested_reviewer.login == 'tech-comm-team-couchbase'
    uses: couchbaselabs/docs-runner/.github/workflows/vale-review.yml@main
    with:
      path: home/
      pull_request_number: ${{ github.event.number }}
      base_sha: ${{ github.event.pull_request.base.sha }}
      head_sha: ${{ github.event.pull_request.head.sha }}
      repository: ${{ github.repository }}
    secrets: inherit
